#pragma once
/*
 * Auto-generated export forwarding header for version.dll
 * Generated by extract_exports.py
 * Inspired by Perfect DLL Proxy (https://github.com/mrexodia/perfect-dll-proxy)
 * 
 * Total Exports: 17 (with ordinals)
 * Original DLL Path: \\.\GLOBALROOT\SystemRoot\System32\version.dll
 * Architecture: x64 only
 * 
 * Usage:
 *   #include "exports/version.h"
 * 
 * This header uses MSVC #pragma directives to forward all exports
 * to the original system DLL without manual function implementation.
 * 
 * The GLOBALROOT path ensures compatibility regardless of Windows
 * installation directory and works at the NT kernel level.
 */

#ifndef VERSION_EXPORTS_H
#define VERSION_EXPORTS_H

// Original DLL path (GLOBALROOT for maximum compatibility)
#define ORIGINAL_DLL "\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll"

// Export forwarding macros (like Perfect DLL Proxy)

// Regular export: Named function with ordinal
#define MAKE_EXPORT(name, ordinal) \
    __pragma(comment(linker, "/EXPORT:" #name "=" ORIGINAL_DLL "." #name ",@" #ordinal))

// COM export: Named function with PRIVATE flag (not in import library)
#define MAKE_EXPORT_PRIVATE(name, ordinal) \
    __pragma(comment(linker, "/EXPORT:" #name "=" ORIGINAL_DLL "." #name ",@" #ordinal ",PRIVATE"))

// Ordinal-only export: No name, only ordinal number with NONAME flag
#define MAKE_EXPORT_ORDINAL(proxy_name, ordinal) \
    __pragma(comment(linker, "/EXPORT:" #proxy_name "=" ORIGINAL_DLL ".#" #ordinal ",@" #ordinal ",NONAME"))

// Regular exports
MAKE_EXPORT(GetFileVersionInfoA, 1)
MAKE_EXPORT(GetFileVersionInfoByHandle, 2)
MAKE_EXPORT(GetFileVersionInfoExA, 3)
MAKE_EXPORT(GetFileVersionInfoExW, 4)
MAKE_EXPORT(GetFileVersionInfoSizeA, 5)
MAKE_EXPORT(GetFileVersionInfoSizeExA, 6)
MAKE_EXPORT(GetFileVersionInfoSizeExW, 7)
MAKE_EXPORT(GetFileVersionInfoSizeW, 8)
MAKE_EXPORT(GetFileVersionInfoW, 9)
MAKE_EXPORT(VerFindFileA, 10)
MAKE_EXPORT(VerFindFileW, 11)
MAKE_EXPORT(VerInstallFileA, 12)
MAKE_EXPORT(VerInstallFileW, 13)
MAKE_EXPORT(VerLanguageNameA, 14)
MAKE_EXPORT(VerLanguageNameW, 15)
MAKE_EXPORT(VerQueryValueA, 16)
MAKE_EXPORT(VerQueryValueW, 17)

#endif // VERSION_EXPORTS_H
