; Auto-generated RUNTIME forwarding thunks for version.dll
; Generated by extract_exports.py (runtime mode)
;
; Each function is a simple JMP through a function pointer.
; The function pointers (orig_*) are defined in version_runtime.h
; and initialized by LoadOriginalDLL() at runtime.
;
; Total thunks: 17
; Architecture: x64 only
; Assembler: MASM (ml64.exe)

.data
EXTERNDEF orig_GetFileVersionInfoA : QWORD
EXTERNDEF orig_GetFileVersionInfoByHandle : QWORD
EXTERNDEF orig_GetFileVersionInfoExA : QWORD
EXTERNDEF orig_GetFileVersionInfoExW : QWORD
EXTERNDEF orig_GetFileVersionInfoSizeA : QWORD
EXTERNDEF orig_GetFileVersionInfoSizeExA : QWORD
EXTERNDEF orig_GetFileVersionInfoSizeExW : QWORD
EXTERNDEF orig_GetFileVersionInfoSizeW : QWORD
EXTERNDEF orig_GetFileVersionInfoW : QWORD
EXTERNDEF orig_VerFindFileA : QWORD
EXTERNDEF orig_VerFindFileW : QWORD
EXTERNDEF orig_VerInstallFileA : QWORD
EXTERNDEF orig_VerInstallFileW : QWORD
EXTERNDEF orig_VerLanguageNameA : QWORD
EXTERNDEF orig_VerLanguageNameW : QWORD
EXTERNDEF orig_VerQueryValueA : QWORD
EXTERNDEF orig_VerQueryValueW : QWORD

.code

__proxy_GetFileVersionInfoA PROC
    jmp QWORD PTR [orig_GetFileVersionInfoA]
__proxy_GetFileVersionInfoA ENDP

__proxy_GetFileVersionInfoByHandle PROC
    jmp QWORD PTR [orig_GetFileVersionInfoByHandle]
__proxy_GetFileVersionInfoByHandle ENDP

__proxy_GetFileVersionInfoExA PROC
    jmp QWORD PTR [orig_GetFileVersionInfoExA]
__proxy_GetFileVersionInfoExA ENDP

__proxy_GetFileVersionInfoExW PROC
    jmp QWORD PTR [orig_GetFileVersionInfoExW]
__proxy_GetFileVersionInfoExW ENDP

__proxy_GetFileVersionInfoSizeA PROC
    jmp QWORD PTR [orig_GetFileVersionInfoSizeA]
__proxy_GetFileVersionInfoSizeA ENDP

__proxy_GetFileVersionInfoSizeExA PROC
    jmp QWORD PTR [orig_GetFileVersionInfoSizeExA]
__proxy_GetFileVersionInfoSizeExA ENDP

__proxy_GetFileVersionInfoSizeExW PROC
    jmp QWORD PTR [orig_GetFileVersionInfoSizeExW]
__proxy_GetFileVersionInfoSizeExW ENDP

__proxy_GetFileVersionInfoSizeW PROC
    jmp QWORD PTR [orig_GetFileVersionInfoSizeW]
__proxy_GetFileVersionInfoSizeW ENDP

__proxy_GetFileVersionInfoW PROC
    jmp QWORD PTR [orig_GetFileVersionInfoW]
__proxy_GetFileVersionInfoW ENDP

__proxy_VerFindFileA PROC
    jmp QWORD PTR [orig_VerFindFileA]
__proxy_VerFindFileA ENDP

__proxy_VerFindFileW PROC
    jmp QWORD PTR [orig_VerFindFileW]
__proxy_VerFindFileW ENDP

__proxy_VerInstallFileA PROC
    jmp QWORD PTR [orig_VerInstallFileA]
__proxy_VerInstallFileA ENDP

__proxy_VerInstallFileW PROC
    jmp QWORD PTR [orig_VerInstallFileW]
__proxy_VerInstallFileW ENDP

__proxy_VerLanguageNameA PROC
    jmp QWORD PTR [orig_VerLanguageNameA]
__proxy_VerLanguageNameA ENDP

__proxy_VerLanguageNameW PROC
    jmp QWORD PTR [orig_VerLanguageNameW]
__proxy_VerLanguageNameW ENDP

__proxy_VerQueryValueA PROC
    jmp QWORD PTR [orig_VerQueryValueA]
__proxy_VerQueryValueA ENDP

__proxy_VerQueryValueW PROC
    jmp QWORD PTR [orig_VerQueryValueW]
__proxy_VerQueryValueW ENDP

END
