#pragma once
/*
 * Auto-generated RUNTIME export forwarding header for version.dll
 * Generated by extract_exports.py (runtime mode)
 *
 * Total Exports: 17 (17 named + 0 ordinal-only)
 * Method: Runtime forwarding (LoadLibrary + GetProcAddress + ASM thunks)
 * Architecture: x64 only
 *
 * This approach is compatible with ALL applications including complex game engines.
 * Unlike linker forwarding, exports are resolved at runtime under our
 * control, avoiding PE loader conflicts with complex game engines.
 *
 * Requires: version_runtime.asm (jump thunks)
 */

#ifndef VERSION_RUNTIME_H
#define VERSION_RUNTIME_H

#include <windows.h>
#include <stdio.h>

// ============================================================
// Function pointer storage (referenced by ASM thunks)
// ============================================================
extern "C" {
    FARPROC orig_GetFileVersionInfoA = NULL;
    FARPROC orig_GetFileVersionInfoByHandle = NULL;
    FARPROC orig_GetFileVersionInfoExA = NULL;
    FARPROC orig_GetFileVersionInfoExW = NULL;
    FARPROC orig_GetFileVersionInfoSizeA = NULL;
    FARPROC orig_GetFileVersionInfoSizeExA = NULL;
    FARPROC orig_GetFileVersionInfoSizeExW = NULL;
    FARPROC orig_GetFileVersionInfoSizeW = NULL;
    FARPROC orig_GetFileVersionInfoW = NULL;
    FARPROC orig_VerFindFileA = NULL;
    FARPROC orig_VerFindFileW = NULL;
    FARPROC orig_VerInstallFileA = NULL;
    FARPROC orig_VerInstallFileW = NULL;
    FARPROC orig_VerLanguageNameA = NULL;
    FARPROC orig_VerLanguageNameW = NULL;
    FARPROC orig_VerQueryValueA = NULL;
    FARPROC orig_VerQueryValueW = NULL;
}

// ============================================================
// Export pragmas (map original names to ASM thunks)
// ============================================================
#pragma comment(linker, "/EXPORT:GetFileVersionInfoA=__proxy_GetFileVersionInfoA,@1")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoByHandle=__proxy_GetFileVersionInfoByHandle,@2")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExA=__proxy_GetFileVersionInfoExA,@3")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExW=__proxy_GetFileVersionInfoExW,@4")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeA=__proxy_GetFileVersionInfoSizeA,@5")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExA=__proxy_GetFileVersionInfoSizeExA,@6")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExW=__proxy_GetFileVersionInfoSizeExW,@7")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeW=__proxy_GetFileVersionInfoSizeW,@8")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoW=__proxy_GetFileVersionInfoW,@9")
#pragma comment(linker, "/EXPORT:VerFindFileA=__proxy_VerFindFileA,@10")
#pragma comment(linker, "/EXPORT:VerFindFileW=__proxy_VerFindFileW,@11")
#pragma comment(linker, "/EXPORT:VerInstallFileA=__proxy_VerInstallFileA,@12")
#pragma comment(linker, "/EXPORT:VerInstallFileW=__proxy_VerInstallFileW,@13")
#pragma comment(linker, "/EXPORT:VerLanguageNameA=__proxy_VerLanguageNameA,@14")
#pragma comment(linker, "/EXPORT:VerLanguageNameW=__proxy_VerLanguageNameW,@15")
#pragma comment(linker, "/EXPORT:VerQueryValueA=__proxy_VerQueryValueA,@16")
#pragma comment(linker, "/EXPORT:VerQueryValueW=__proxy_VerQueryValueW,@17")

// ============================================================
// Load original DLL and resolve all function pointers
// Call this from DllMain(DLL_PROCESS_ATTACH)
// ============================================================
inline bool LoadOriginalDLL() {
    // Get System32 directory dynamically (works on all Windows installs)
    char sysDir[MAX_PATH];
    GetSystemDirectoryA(sysDir, MAX_PATH);

    char dllPath[MAX_PATH];
    sprintf_s(dllPath, MAX_PATH, "%s\\version.dll", sysDir);

    HMODULE hOriginal = LoadLibraryA(dllPath);
    if (!hOriginal) {
        return false;
    }

    // Resolve all function pointers
    orig_GetFileVersionInfoA = GetProcAddress(hOriginal, "GetFileVersionInfoA");
    orig_GetFileVersionInfoByHandle = GetProcAddress(hOriginal, "GetFileVersionInfoByHandle");
    orig_GetFileVersionInfoExA = GetProcAddress(hOriginal, "GetFileVersionInfoExA");
    orig_GetFileVersionInfoExW = GetProcAddress(hOriginal, "GetFileVersionInfoExW");
    orig_GetFileVersionInfoSizeA = GetProcAddress(hOriginal, "GetFileVersionInfoSizeA");
    orig_GetFileVersionInfoSizeExA = GetProcAddress(hOriginal, "GetFileVersionInfoSizeExA");
    orig_GetFileVersionInfoSizeExW = GetProcAddress(hOriginal, "GetFileVersionInfoSizeExW");
    orig_GetFileVersionInfoSizeW = GetProcAddress(hOriginal, "GetFileVersionInfoSizeW");
    orig_GetFileVersionInfoW = GetProcAddress(hOriginal, "GetFileVersionInfoW");
    orig_VerFindFileA = GetProcAddress(hOriginal, "VerFindFileA");
    orig_VerFindFileW = GetProcAddress(hOriginal, "VerFindFileW");
    orig_VerInstallFileA = GetProcAddress(hOriginal, "VerInstallFileA");
    orig_VerInstallFileW = GetProcAddress(hOriginal, "VerInstallFileW");
    orig_VerLanguageNameA = GetProcAddress(hOriginal, "VerLanguageNameA");
    orig_VerLanguageNameW = GetProcAddress(hOriginal, "VerLanguageNameW");
    orig_VerQueryValueA = GetProcAddress(hOriginal, "VerQueryValueA");
    orig_VerQueryValueW = GetProcAddress(hOriginal, "VerQueryValueW");

    return true;
}

#endif // VERSION_RUNTIME_H
