#pragma once
/*
 * Auto-generated RUNTIME export forwarding header for winhttp.dll
 * Generated by extract_exports.py (runtime mode)
 *
 * Total Exports: 91 (91 named + 0 ordinal-only)
 * Method: Runtime forwarding (LoadLibrary + GetProcAddress + ASM thunks)
 * Architecture: x64 only
 *
 * This approach is compatible with ALL applications including complex game engines.
 * Unlike linker forwarding, exports are resolved at runtime under our
 * control, avoiding PE loader conflicts with complex game engines.
 *
 * Requires: winhttp_runtime.asm (jump thunks)
 */

#ifndef WINHTTP_RUNTIME_H
#define WINHTTP_RUNTIME_H

#include <windows.h>
#include <stdio.h>

// ============================================================
// Function pointer storage (referenced by ASM thunks)
// ============================================================
extern "C" {
    FARPROC orig_Private1 = NULL;
    FARPROC orig_SvchostPushServiceGlobals = NULL;
    FARPROC orig_WinHttpAddRequestHeaders = NULL;
    FARPROC orig_WinHttpAddRequestHeadersEx = NULL;
    FARPROC orig_WinHttpAutoProxySvcMain = NULL;
    FARPROC orig_WinHttpCheckPlatform = NULL;
    FARPROC orig_WinHttpCloseHandle = NULL;
    FARPROC orig_WinHttpConnect = NULL;
    FARPROC orig_WinHttpConnectionDeletePolicyEntries = NULL;
    FARPROC orig_WinHttpConnectionDeleteProxyInfo = NULL;
    FARPROC orig_WinHttpConnectionFreeNameList = NULL;
    FARPROC orig_WinHttpConnectionFreeProxyInfo = NULL;
    FARPROC orig_WinHttpConnectionFreeProxyList = NULL;
    FARPROC orig_WinHttpConnectionGetNameList = NULL;
    FARPROC orig_WinHttpConnectionGetProxyInfo = NULL;
    FARPROC orig_WinHttpConnectionGetProxyList = NULL;
    FARPROC orig_WinHttpConnectionOnlyConvert = NULL;
    FARPROC orig_WinHttpConnectionOnlyReceive = NULL;
    FARPROC orig_WinHttpConnectionOnlySend = NULL;
    FARPROC orig_WinHttpConnectionSetPolicyEntries = NULL;
    FARPROC orig_WinHttpConnectionSetProxyInfo = NULL;
    FARPROC orig_WinHttpConnectionUpdateIfIndexTable = NULL;
    FARPROC orig_WinHttpCrackUrl = NULL;
    FARPROC orig_WinHttpCreateProxyList = NULL;
    FARPROC orig_WinHttpCreateProxyManager = NULL;
    FARPROC orig_WinHttpCreateProxyResolver = NULL;
    FARPROC orig_WinHttpCreateProxyResult = NULL;
    FARPROC orig_WinHttpCreateUiCompatibleProxyString = NULL;
    FARPROC orig_WinHttpCreateUrl = NULL;
    FARPROC orig_WinHttpDetectAutoProxyConfigUrl = NULL;
    FARPROC orig_WinHttpFreeProxyResult = NULL;
    FARPROC orig_WinHttpFreeProxyResultEx = NULL;
    FARPROC orig_WinHttpFreeProxySettings = NULL;
    FARPROC orig_WinHttpFreeProxySettingsEx = NULL;
    FARPROC orig_WinHttpFreeQueryConnectionGroupResult = NULL;
    FARPROC orig_WinHttpGetDefaultProxyConfiguration = NULL;
    FARPROC orig_WinHttpGetIEProxyConfigForCurrentUser = NULL;
    FARPROC orig_WinHttpGetProxyForUrl = NULL;
    FARPROC orig_WinHttpGetProxyForUrlEx = NULL;
    FARPROC orig_WinHttpGetProxyForUrlEx2 = NULL;
    FARPROC orig_WinHttpGetProxyForUrlHvsi = NULL;
    FARPROC orig_WinHttpGetProxyResult = NULL;
    FARPROC orig_WinHttpGetProxyResultEx = NULL;
    FARPROC orig_WinHttpGetProxySettingsEx = NULL;
    FARPROC orig_WinHttpGetProxySettingsResultEx = NULL;
    FARPROC orig_WinHttpGetProxySettingsVersion = NULL;
    FARPROC orig_WinHttpGetTunnelSocket = NULL;
    FARPROC orig_WinHttpOpen = NULL;
    FARPROC orig_WinHttpOpenRequest = NULL;
    FARPROC orig_WinHttpPacJsWorkerMain = NULL;
    FARPROC orig_WinHttpProbeConnectivity = NULL;
    FARPROC orig_WinHttpProtocolCompleteUpgrade = NULL;
    FARPROC orig_WinHttpProtocolReceive = NULL;
    FARPROC orig_WinHttpProtocolSend = NULL;
    FARPROC orig_WinHttpQueryAuthSchemes = NULL;
    FARPROC orig_WinHttpQueryConnectionGroup = NULL;
    FARPROC orig_WinHttpQueryDataAvailable = NULL;
    FARPROC orig_WinHttpQueryHeaders = NULL;
    FARPROC orig_WinHttpQueryHeadersEx = NULL;
    FARPROC orig_WinHttpQueryOption = NULL;
    FARPROC orig_WinHttpReadData = NULL;
    FARPROC orig_WinHttpReadDataEx = NULL;
    FARPROC orig_WinHttpReadProxySettings = NULL;
    FARPROC orig_WinHttpReadProxySettingsHvsi = NULL;
    FARPROC orig_WinHttpReceiveResponse = NULL;
    FARPROC orig_WinHttpRefreshProxySettings = NULL;
    FARPROC orig_WinHttpRegisterProxyChangeNotification = NULL;
    FARPROC orig_WinHttpResetAutoProxy = NULL;
    FARPROC orig_WinHttpResolverGetProxyForUrl = NULL;
    FARPROC orig_WinHttpSaveProxyCredentials = NULL;
    FARPROC orig_WinHttpSendRequest = NULL;
    FARPROC orig_WinHttpSetCredentials = NULL;
    FARPROC orig_WinHttpSetDefaultProxyConfiguration = NULL;
    FARPROC orig_WinHttpSetOption = NULL;
    FARPROC orig_WinHttpSetProxySettingsPerUser = NULL;
    FARPROC orig_WinHttpSetSecureLegacyServersAppCompat = NULL;
    FARPROC orig_WinHttpSetStatusCallback = NULL;
    FARPROC orig_WinHttpSetTimeouts = NULL;
    FARPROC orig_WinHttpTimeFromSystemTime = NULL;
    FARPROC orig_WinHttpTimeToSystemTime = NULL;
    FARPROC orig_WinHttpUnregisterProxyChangeNotification = NULL;
    FARPROC orig_WinHttpWebSocketClose = NULL;
    FARPROC orig_WinHttpWebSocketCompleteUpgrade = NULL;
    FARPROC orig_WinHttpWebSocketQueryCloseStatus = NULL;
    FARPROC orig_WinHttpWebSocketReceive = NULL;
    FARPROC orig_WinHttpWebSocketSend = NULL;
    FARPROC orig_WinHttpWebSocketShutdown = NULL;
    FARPROC orig_WinHttpWriteData = NULL;
    FARPROC orig_WinHttpWriteProxySettings = NULL;
    FARPROC orig_DllCanUnloadNow = NULL;
    FARPROC orig_DllGetClassObject = NULL;
}

// ============================================================
// Export pragmas (map original names to ASM thunks)
// ============================================================
#pragma comment(linker, "/EXPORT:Private1=__proxy_Private1,@3")
#pragma comment(linker, "/EXPORT:SvchostPushServiceGlobals=__proxy_SvchostPushServiceGlobals,@4")
#pragma comment(linker, "/EXPORT:WinHttpAddRequestHeaders=__proxy_WinHttpAddRequestHeaders,@5")
#pragma comment(linker, "/EXPORT:WinHttpAddRequestHeadersEx=__proxy_WinHttpAddRequestHeadersEx,@6")
#pragma comment(linker, "/EXPORT:WinHttpAutoProxySvcMain=__proxy_WinHttpAutoProxySvcMain,@7")
#pragma comment(linker, "/EXPORT:WinHttpCheckPlatform=__proxy_WinHttpCheckPlatform,@8")
#pragma comment(linker, "/EXPORT:WinHttpCloseHandle=__proxy_WinHttpCloseHandle,@9")
#pragma comment(linker, "/EXPORT:WinHttpConnect=__proxy_WinHttpConnect,@10")
#pragma comment(linker, "/EXPORT:WinHttpConnectionDeletePolicyEntries=__proxy_WinHttpConnectionDeletePolicyEntries,@11")
#pragma comment(linker, "/EXPORT:WinHttpConnectionDeleteProxyInfo=__proxy_WinHttpConnectionDeleteProxyInfo,@12")
#pragma comment(linker, "/EXPORT:WinHttpConnectionFreeNameList=__proxy_WinHttpConnectionFreeNameList,@13")
#pragma comment(linker, "/EXPORT:WinHttpConnectionFreeProxyInfo=__proxy_WinHttpConnectionFreeProxyInfo,@14")
#pragma comment(linker, "/EXPORT:WinHttpConnectionFreeProxyList=__proxy_WinHttpConnectionFreeProxyList,@15")
#pragma comment(linker, "/EXPORT:WinHttpConnectionGetNameList=__proxy_WinHttpConnectionGetNameList,@16")
#pragma comment(linker, "/EXPORT:WinHttpConnectionGetProxyInfo=__proxy_WinHttpConnectionGetProxyInfo,@17")
#pragma comment(linker, "/EXPORT:WinHttpConnectionGetProxyList=__proxy_WinHttpConnectionGetProxyList,@18")
#pragma comment(linker, "/EXPORT:WinHttpConnectionOnlyConvert=__proxy_WinHttpConnectionOnlyConvert,@19")
#pragma comment(linker, "/EXPORT:WinHttpConnectionOnlyReceive=__proxy_WinHttpConnectionOnlyReceive,@20")
#pragma comment(linker, "/EXPORT:WinHttpConnectionOnlySend=__proxy_WinHttpConnectionOnlySend,@21")
#pragma comment(linker, "/EXPORT:WinHttpConnectionSetPolicyEntries=__proxy_WinHttpConnectionSetPolicyEntries,@22")
#pragma comment(linker, "/EXPORT:WinHttpConnectionSetProxyInfo=__proxy_WinHttpConnectionSetProxyInfo,@23")
#pragma comment(linker, "/EXPORT:WinHttpConnectionUpdateIfIndexTable=__proxy_WinHttpConnectionUpdateIfIndexTable,@24")
#pragma comment(linker, "/EXPORT:WinHttpCrackUrl=__proxy_WinHttpCrackUrl,@25")
#pragma comment(linker, "/EXPORT:WinHttpCreateProxyList=__proxy_WinHttpCreateProxyList,@26")
#pragma comment(linker, "/EXPORT:WinHttpCreateProxyManager=__proxy_WinHttpCreateProxyManager,@27")
#pragma comment(linker, "/EXPORT:WinHttpCreateProxyResolver=__proxy_WinHttpCreateProxyResolver,@28")
#pragma comment(linker, "/EXPORT:WinHttpCreateProxyResult=__proxy_WinHttpCreateProxyResult,@29")
#pragma comment(linker, "/EXPORT:WinHttpCreateUiCompatibleProxyString=__proxy_WinHttpCreateUiCompatibleProxyString,@30")
#pragma comment(linker, "/EXPORT:WinHttpCreateUrl=__proxy_WinHttpCreateUrl,@31")
#pragma comment(linker, "/EXPORT:WinHttpDetectAutoProxyConfigUrl=__proxy_WinHttpDetectAutoProxyConfigUrl,@32")
#pragma comment(linker, "/EXPORT:WinHttpFreeProxyResult=__proxy_WinHttpFreeProxyResult,@33")
#pragma comment(linker, "/EXPORT:WinHttpFreeProxyResultEx=__proxy_WinHttpFreeProxyResultEx,@34")
#pragma comment(linker, "/EXPORT:WinHttpFreeProxySettings=__proxy_WinHttpFreeProxySettings,@35")
#pragma comment(linker, "/EXPORT:WinHttpFreeProxySettingsEx=__proxy_WinHttpFreeProxySettingsEx,@36")
#pragma comment(linker, "/EXPORT:WinHttpFreeQueryConnectionGroupResult=__proxy_WinHttpFreeQueryConnectionGroupResult,@37")
#pragma comment(linker, "/EXPORT:WinHttpGetDefaultProxyConfiguration=__proxy_WinHttpGetDefaultProxyConfiguration,@38")
#pragma comment(linker, "/EXPORT:WinHttpGetIEProxyConfigForCurrentUser=__proxy_WinHttpGetIEProxyConfigForCurrentUser,@39")
#pragma comment(linker, "/EXPORT:WinHttpGetProxyForUrl=__proxy_WinHttpGetProxyForUrl,@40")
#pragma comment(linker, "/EXPORT:WinHttpGetProxyForUrlEx=__proxy_WinHttpGetProxyForUrlEx,@41")
#pragma comment(linker, "/EXPORT:WinHttpGetProxyForUrlEx2=__proxy_WinHttpGetProxyForUrlEx2,@42")
#pragma comment(linker, "/EXPORT:WinHttpGetProxyForUrlHvsi=__proxy_WinHttpGetProxyForUrlHvsi,@43")
#pragma comment(linker, "/EXPORT:WinHttpGetProxyResult=__proxy_WinHttpGetProxyResult,@44")
#pragma comment(linker, "/EXPORT:WinHttpGetProxyResultEx=__proxy_WinHttpGetProxyResultEx,@45")
#pragma comment(linker, "/EXPORT:WinHttpGetProxySettingsEx=__proxy_WinHttpGetProxySettingsEx,@46")
#pragma comment(linker, "/EXPORT:WinHttpGetProxySettingsResultEx=__proxy_WinHttpGetProxySettingsResultEx,@47")
#pragma comment(linker, "/EXPORT:WinHttpGetProxySettingsVersion=__proxy_WinHttpGetProxySettingsVersion,@48")
#pragma comment(linker, "/EXPORT:WinHttpGetTunnelSocket=__proxy_WinHttpGetTunnelSocket,@49")
#pragma comment(linker, "/EXPORT:WinHttpOpen=__proxy_WinHttpOpen,@50")
#pragma comment(linker, "/EXPORT:WinHttpOpenRequest=__proxy_WinHttpOpenRequest,@51")
#pragma comment(linker, "/EXPORT:WinHttpPacJsWorkerMain=__proxy_WinHttpPacJsWorkerMain,@52")
#pragma comment(linker, "/EXPORT:WinHttpProbeConnectivity=__proxy_WinHttpProbeConnectivity,@53")
#pragma comment(linker, "/EXPORT:WinHttpProtocolCompleteUpgrade=__proxy_WinHttpProtocolCompleteUpgrade,@54")
#pragma comment(linker, "/EXPORT:WinHttpProtocolReceive=__proxy_WinHttpProtocolReceive,@55")
#pragma comment(linker, "/EXPORT:WinHttpProtocolSend=__proxy_WinHttpProtocolSend,@56")
#pragma comment(linker, "/EXPORT:WinHttpQueryAuthSchemes=__proxy_WinHttpQueryAuthSchemes,@57")
#pragma comment(linker, "/EXPORT:WinHttpQueryConnectionGroup=__proxy_WinHttpQueryConnectionGroup,@58")
#pragma comment(linker, "/EXPORT:WinHttpQueryDataAvailable=__proxy_WinHttpQueryDataAvailable,@59")
#pragma comment(linker, "/EXPORT:WinHttpQueryHeaders=__proxy_WinHttpQueryHeaders,@60")
#pragma comment(linker, "/EXPORT:WinHttpQueryHeadersEx=__proxy_WinHttpQueryHeadersEx,@61")
#pragma comment(linker, "/EXPORT:WinHttpQueryOption=__proxy_WinHttpQueryOption,@62")
#pragma comment(linker, "/EXPORT:WinHttpReadData=__proxy_WinHttpReadData,@63")
#pragma comment(linker, "/EXPORT:WinHttpReadDataEx=__proxy_WinHttpReadDataEx,@64")
#pragma comment(linker, "/EXPORT:WinHttpReadProxySettings=__proxy_WinHttpReadProxySettings,@65")
#pragma comment(linker, "/EXPORT:WinHttpReadProxySettingsHvsi=__proxy_WinHttpReadProxySettingsHvsi,@66")
#pragma comment(linker, "/EXPORT:WinHttpReceiveResponse=__proxy_WinHttpReceiveResponse,@67")
#pragma comment(linker, "/EXPORT:WinHttpRefreshProxySettings=__proxy_WinHttpRefreshProxySettings,@68")
#pragma comment(linker, "/EXPORT:WinHttpRegisterProxyChangeNotification=__proxy_WinHttpRegisterProxyChangeNotification,@69")
#pragma comment(linker, "/EXPORT:WinHttpResetAutoProxy=__proxy_WinHttpResetAutoProxy,@70")
#pragma comment(linker, "/EXPORT:WinHttpResolverGetProxyForUrl=__proxy_WinHttpResolverGetProxyForUrl,@71")
#pragma comment(linker, "/EXPORT:WinHttpSaveProxyCredentials=__proxy_WinHttpSaveProxyCredentials,@72")
#pragma comment(linker, "/EXPORT:WinHttpSendRequest=__proxy_WinHttpSendRequest,@73")
#pragma comment(linker, "/EXPORT:WinHttpSetCredentials=__proxy_WinHttpSetCredentials,@74")
#pragma comment(linker, "/EXPORT:WinHttpSetDefaultProxyConfiguration=__proxy_WinHttpSetDefaultProxyConfiguration,@75")
#pragma comment(linker, "/EXPORT:WinHttpSetOption=__proxy_WinHttpSetOption,@76")
#pragma comment(linker, "/EXPORT:WinHttpSetProxySettingsPerUser=__proxy_WinHttpSetProxySettingsPerUser,@77")
#pragma comment(linker, "/EXPORT:WinHttpSetSecureLegacyServersAppCompat=__proxy_WinHttpSetSecureLegacyServersAppCompat,@78")
#pragma comment(linker, "/EXPORT:WinHttpSetStatusCallback=__proxy_WinHttpSetStatusCallback,@79")
#pragma comment(linker, "/EXPORT:WinHttpSetTimeouts=__proxy_WinHttpSetTimeouts,@80")
#pragma comment(linker, "/EXPORT:WinHttpTimeFromSystemTime=__proxy_WinHttpTimeFromSystemTime,@81")
#pragma comment(linker, "/EXPORT:WinHttpTimeToSystemTime=__proxy_WinHttpTimeToSystemTime,@82")
#pragma comment(linker, "/EXPORT:WinHttpUnregisterProxyChangeNotification=__proxy_WinHttpUnregisterProxyChangeNotification,@83")
#pragma comment(linker, "/EXPORT:WinHttpWebSocketClose=__proxy_WinHttpWebSocketClose,@84")
#pragma comment(linker, "/EXPORT:WinHttpWebSocketCompleteUpgrade=__proxy_WinHttpWebSocketCompleteUpgrade,@85")
#pragma comment(linker, "/EXPORT:WinHttpWebSocketQueryCloseStatus=__proxy_WinHttpWebSocketQueryCloseStatus,@86")
#pragma comment(linker, "/EXPORT:WinHttpWebSocketReceive=__proxy_WinHttpWebSocketReceive,@87")
#pragma comment(linker, "/EXPORT:WinHttpWebSocketSend=__proxy_WinHttpWebSocketSend,@88")
#pragma comment(linker, "/EXPORT:WinHttpWebSocketShutdown=__proxy_WinHttpWebSocketShutdown,@89")
#pragma comment(linker, "/EXPORT:WinHttpWriteData=__proxy_WinHttpWriteData,@90")
#pragma comment(linker, "/EXPORT:WinHttpWriteProxySettings=__proxy_WinHttpWriteProxySettings,@91")
#pragma comment(linker, "/EXPORT:DllCanUnloadNow=__proxy_DllCanUnloadNow,@1,PRIVATE")
#pragma comment(linker, "/EXPORT:DllGetClassObject=__proxy_DllGetClassObject,@2,PRIVATE")

// ============================================================
// Load original DLL and resolve all function pointers
// Call this from DllMain(DLL_PROCESS_ATTACH)
// ============================================================
inline bool LoadOriginalDLL() {
    // Get System32 directory dynamically (works on all Windows installs)
    char sysDir[MAX_PATH];
    GetSystemDirectoryA(sysDir, MAX_PATH);

    char dllPath[MAX_PATH];
    sprintf_s(dllPath, MAX_PATH, "%s\\winhttp.dll", sysDir);

    HMODULE hOriginal = LoadLibraryA(dllPath);
    if (!hOriginal) {
        return false;
    }

    // Resolve all function pointers
    orig_Private1 = GetProcAddress(hOriginal, "Private1");
    orig_SvchostPushServiceGlobals = GetProcAddress(hOriginal, "SvchostPushServiceGlobals");
    orig_WinHttpAddRequestHeaders = GetProcAddress(hOriginal, "WinHttpAddRequestHeaders");
    orig_WinHttpAddRequestHeadersEx = GetProcAddress(hOriginal, "WinHttpAddRequestHeadersEx");
    orig_WinHttpAutoProxySvcMain = GetProcAddress(hOriginal, "WinHttpAutoProxySvcMain");
    orig_WinHttpCheckPlatform = GetProcAddress(hOriginal, "WinHttpCheckPlatform");
    orig_WinHttpCloseHandle = GetProcAddress(hOriginal, "WinHttpCloseHandle");
    orig_WinHttpConnect = GetProcAddress(hOriginal, "WinHttpConnect");
    orig_WinHttpConnectionDeletePolicyEntries = GetProcAddress(hOriginal, "WinHttpConnectionDeletePolicyEntries");
    orig_WinHttpConnectionDeleteProxyInfo = GetProcAddress(hOriginal, "WinHttpConnectionDeleteProxyInfo");
    orig_WinHttpConnectionFreeNameList = GetProcAddress(hOriginal, "WinHttpConnectionFreeNameList");
    orig_WinHttpConnectionFreeProxyInfo = GetProcAddress(hOriginal, "WinHttpConnectionFreeProxyInfo");
    orig_WinHttpConnectionFreeProxyList = GetProcAddress(hOriginal, "WinHttpConnectionFreeProxyList");
    orig_WinHttpConnectionGetNameList = GetProcAddress(hOriginal, "WinHttpConnectionGetNameList");
    orig_WinHttpConnectionGetProxyInfo = GetProcAddress(hOriginal, "WinHttpConnectionGetProxyInfo");
    orig_WinHttpConnectionGetProxyList = GetProcAddress(hOriginal, "WinHttpConnectionGetProxyList");
    orig_WinHttpConnectionOnlyConvert = GetProcAddress(hOriginal, "WinHttpConnectionOnlyConvert");
    orig_WinHttpConnectionOnlyReceive = GetProcAddress(hOriginal, "WinHttpConnectionOnlyReceive");
    orig_WinHttpConnectionOnlySend = GetProcAddress(hOriginal, "WinHttpConnectionOnlySend");
    orig_WinHttpConnectionSetPolicyEntries = GetProcAddress(hOriginal, "WinHttpConnectionSetPolicyEntries");
    orig_WinHttpConnectionSetProxyInfo = GetProcAddress(hOriginal, "WinHttpConnectionSetProxyInfo");
    orig_WinHttpConnectionUpdateIfIndexTable = GetProcAddress(hOriginal, "WinHttpConnectionUpdateIfIndexTable");
    orig_WinHttpCrackUrl = GetProcAddress(hOriginal, "WinHttpCrackUrl");
    orig_WinHttpCreateProxyList = GetProcAddress(hOriginal, "WinHttpCreateProxyList");
    orig_WinHttpCreateProxyManager = GetProcAddress(hOriginal, "WinHttpCreateProxyManager");
    orig_WinHttpCreateProxyResolver = GetProcAddress(hOriginal, "WinHttpCreateProxyResolver");
    orig_WinHttpCreateProxyResult = GetProcAddress(hOriginal, "WinHttpCreateProxyResult");
    orig_WinHttpCreateUiCompatibleProxyString = GetProcAddress(hOriginal, "WinHttpCreateUiCompatibleProxyString");
    orig_WinHttpCreateUrl = GetProcAddress(hOriginal, "WinHttpCreateUrl");
    orig_WinHttpDetectAutoProxyConfigUrl = GetProcAddress(hOriginal, "WinHttpDetectAutoProxyConfigUrl");
    orig_WinHttpFreeProxyResult = GetProcAddress(hOriginal, "WinHttpFreeProxyResult");
    orig_WinHttpFreeProxyResultEx = GetProcAddress(hOriginal, "WinHttpFreeProxyResultEx");
    orig_WinHttpFreeProxySettings = GetProcAddress(hOriginal, "WinHttpFreeProxySettings");
    orig_WinHttpFreeProxySettingsEx = GetProcAddress(hOriginal, "WinHttpFreeProxySettingsEx");
    orig_WinHttpFreeQueryConnectionGroupResult = GetProcAddress(hOriginal, "WinHttpFreeQueryConnectionGroupResult");
    orig_WinHttpGetDefaultProxyConfiguration = GetProcAddress(hOriginal, "WinHttpGetDefaultProxyConfiguration");
    orig_WinHttpGetIEProxyConfigForCurrentUser = GetProcAddress(hOriginal, "WinHttpGetIEProxyConfigForCurrentUser");
    orig_WinHttpGetProxyForUrl = GetProcAddress(hOriginal, "WinHttpGetProxyForUrl");
    orig_WinHttpGetProxyForUrlEx = GetProcAddress(hOriginal, "WinHttpGetProxyForUrlEx");
    orig_WinHttpGetProxyForUrlEx2 = GetProcAddress(hOriginal, "WinHttpGetProxyForUrlEx2");
    orig_WinHttpGetProxyForUrlHvsi = GetProcAddress(hOriginal, "WinHttpGetProxyForUrlHvsi");
    orig_WinHttpGetProxyResult = GetProcAddress(hOriginal, "WinHttpGetProxyResult");
    orig_WinHttpGetProxyResultEx = GetProcAddress(hOriginal, "WinHttpGetProxyResultEx");
    orig_WinHttpGetProxySettingsEx = GetProcAddress(hOriginal, "WinHttpGetProxySettingsEx");
    orig_WinHttpGetProxySettingsResultEx = GetProcAddress(hOriginal, "WinHttpGetProxySettingsResultEx");
    orig_WinHttpGetProxySettingsVersion = GetProcAddress(hOriginal, "WinHttpGetProxySettingsVersion");
    orig_WinHttpGetTunnelSocket = GetProcAddress(hOriginal, "WinHttpGetTunnelSocket");
    orig_WinHttpOpen = GetProcAddress(hOriginal, "WinHttpOpen");
    orig_WinHttpOpenRequest = GetProcAddress(hOriginal, "WinHttpOpenRequest");
    orig_WinHttpPacJsWorkerMain = GetProcAddress(hOriginal, "WinHttpPacJsWorkerMain");
    orig_WinHttpProbeConnectivity = GetProcAddress(hOriginal, "WinHttpProbeConnectivity");
    orig_WinHttpProtocolCompleteUpgrade = GetProcAddress(hOriginal, "WinHttpProtocolCompleteUpgrade");
    orig_WinHttpProtocolReceive = GetProcAddress(hOriginal, "WinHttpProtocolReceive");
    orig_WinHttpProtocolSend = GetProcAddress(hOriginal, "WinHttpProtocolSend");
    orig_WinHttpQueryAuthSchemes = GetProcAddress(hOriginal, "WinHttpQueryAuthSchemes");
    orig_WinHttpQueryConnectionGroup = GetProcAddress(hOriginal, "WinHttpQueryConnectionGroup");
    orig_WinHttpQueryDataAvailable = GetProcAddress(hOriginal, "WinHttpQueryDataAvailable");
    orig_WinHttpQueryHeaders = GetProcAddress(hOriginal, "WinHttpQueryHeaders");
    orig_WinHttpQueryHeadersEx = GetProcAddress(hOriginal, "WinHttpQueryHeadersEx");
    orig_WinHttpQueryOption = GetProcAddress(hOriginal, "WinHttpQueryOption");
    orig_WinHttpReadData = GetProcAddress(hOriginal, "WinHttpReadData");
    orig_WinHttpReadDataEx = GetProcAddress(hOriginal, "WinHttpReadDataEx");
    orig_WinHttpReadProxySettings = GetProcAddress(hOriginal, "WinHttpReadProxySettings");
    orig_WinHttpReadProxySettingsHvsi = GetProcAddress(hOriginal, "WinHttpReadProxySettingsHvsi");
    orig_WinHttpReceiveResponse = GetProcAddress(hOriginal, "WinHttpReceiveResponse");
    orig_WinHttpRefreshProxySettings = GetProcAddress(hOriginal, "WinHttpRefreshProxySettings");
    orig_WinHttpRegisterProxyChangeNotification = GetProcAddress(hOriginal, "WinHttpRegisterProxyChangeNotification");
    orig_WinHttpResetAutoProxy = GetProcAddress(hOriginal, "WinHttpResetAutoProxy");
    orig_WinHttpResolverGetProxyForUrl = GetProcAddress(hOriginal, "WinHttpResolverGetProxyForUrl");
    orig_WinHttpSaveProxyCredentials = GetProcAddress(hOriginal, "WinHttpSaveProxyCredentials");
    orig_WinHttpSendRequest = GetProcAddress(hOriginal, "WinHttpSendRequest");
    orig_WinHttpSetCredentials = GetProcAddress(hOriginal, "WinHttpSetCredentials");
    orig_WinHttpSetDefaultProxyConfiguration = GetProcAddress(hOriginal, "WinHttpSetDefaultProxyConfiguration");
    orig_WinHttpSetOption = GetProcAddress(hOriginal, "WinHttpSetOption");
    orig_WinHttpSetProxySettingsPerUser = GetProcAddress(hOriginal, "WinHttpSetProxySettingsPerUser");
    orig_WinHttpSetSecureLegacyServersAppCompat = GetProcAddress(hOriginal, "WinHttpSetSecureLegacyServersAppCompat");
    orig_WinHttpSetStatusCallback = GetProcAddress(hOriginal, "WinHttpSetStatusCallback");
    orig_WinHttpSetTimeouts = GetProcAddress(hOriginal, "WinHttpSetTimeouts");
    orig_WinHttpTimeFromSystemTime = GetProcAddress(hOriginal, "WinHttpTimeFromSystemTime");
    orig_WinHttpTimeToSystemTime = GetProcAddress(hOriginal, "WinHttpTimeToSystemTime");
    orig_WinHttpUnregisterProxyChangeNotification = GetProcAddress(hOriginal, "WinHttpUnregisterProxyChangeNotification");
    orig_WinHttpWebSocketClose = GetProcAddress(hOriginal, "WinHttpWebSocketClose");
    orig_WinHttpWebSocketCompleteUpgrade = GetProcAddress(hOriginal, "WinHttpWebSocketCompleteUpgrade");
    orig_WinHttpWebSocketQueryCloseStatus = GetProcAddress(hOriginal, "WinHttpWebSocketQueryCloseStatus");
    orig_WinHttpWebSocketReceive = GetProcAddress(hOriginal, "WinHttpWebSocketReceive");
    orig_WinHttpWebSocketSend = GetProcAddress(hOriginal, "WinHttpWebSocketSend");
    orig_WinHttpWebSocketShutdown = GetProcAddress(hOriginal, "WinHttpWebSocketShutdown");
    orig_WinHttpWriteData = GetProcAddress(hOriginal, "WinHttpWriteData");
    orig_WinHttpWriteProxySettings = GetProcAddress(hOriginal, "WinHttpWriteProxySettings");
    orig_DllCanUnloadNow = GetProcAddress(hOriginal, "DllCanUnloadNow");
    orig_DllGetClassObject = GetProcAddress(hOriginal, "DllGetClassObject");

    return true;
}

#endif // WINHTTP_RUNTIME_H
