#pragma once
/*
 * Auto-generated export forwarding header for winhttp.dll
 * Generated by extract_exports.py
 * Inspired by Perfect DLL Proxy (https://github.com/mrexodia/perfect-dll-proxy)
 * 
 * Total Exports: 91 (with ordinals) - 89 regular, 2 COM/PRIVATE
 * Original DLL Path: \\.\GLOBALROOT\SystemRoot\System32\winhttp.dll
 * Architecture: x64 only
 * 
 * Usage:
 *   #include "exports/winhttp.h"
 * 
 * This header uses MSVC #pragma directives to forward all exports
 * to the original system DLL without manual function implementation.
 * 
 * The GLOBALROOT path ensures compatibility regardless of Windows
 * installation directory and works at the NT kernel level.
 */

#ifndef WINHTTP_EXPORTS_H
#define WINHTTP_EXPORTS_H

// Original DLL path (GLOBALROOT for maximum compatibility)
#define ORIGINAL_DLL "\\\\.\\GLOBALROOT\\SystemRoot\\System32\\winhttp.dll"

// Export forwarding macros (like Perfect DLL Proxy)

// Regular export: Named function with ordinal
#define MAKE_EXPORT(name, ordinal) \
    __pragma(comment(linker, "/EXPORT:" #name "=" ORIGINAL_DLL "." #name ",@" #ordinal))

// COM export: Named function with PRIVATE flag (not in import library)
#define MAKE_EXPORT_PRIVATE(name, ordinal) \
    __pragma(comment(linker, "/EXPORT:" #name "=" ORIGINAL_DLL "." #name ",@" #ordinal ",PRIVATE"))

// Ordinal-only export: No name, only ordinal number with NONAME flag
#define MAKE_EXPORT_ORDINAL(proxy_name, ordinal) \
    __pragma(comment(linker, "/EXPORT:" #proxy_name "=" ORIGINAL_DLL ".#" #ordinal ",@" #ordinal ",NONAME"))

// Regular exports
MAKE_EXPORT(Private1, 3)
MAKE_EXPORT(SvchostPushServiceGlobals, 4)
MAKE_EXPORT(WinHttpAddRequestHeaders, 5)
MAKE_EXPORT(WinHttpAddRequestHeadersEx, 6)
MAKE_EXPORT(WinHttpAutoProxySvcMain, 7)
MAKE_EXPORT(WinHttpCheckPlatform, 8)
MAKE_EXPORT(WinHttpCloseHandle, 9)
MAKE_EXPORT(WinHttpConnect, 10)
MAKE_EXPORT(WinHttpConnectionDeletePolicyEntries, 11)
MAKE_EXPORT(WinHttpConnectionDeleteProxyInfo, 12)
MAKE_EXPORT(WinHttpConnectionFreeNameList, 13)
MAKE_EXPORT(WinHttpConnectionFreeProxyInfo, 14)
MAKE_EXPORT(WinHttpConnectionFreeProxyList, 15)
MAKE_EXPORT(WinHttpConnectionGetNameList, 16)
MAKE_EXPORT(WinHttpConnectionGetProxyInfo, 17)
MAKE_EXPORT(WinHttpConnectionGetProxyList, 18)
MAKE_EXPORT(WinHttpConnectionOnlyConvert, 19)
MAKE_EXPORT(WinHttpConnectionOnlyReceive, 20)
MAKE_EXPORT(WinHttpConnectionOnlySend, 21)
MAKE_EXPORT(WinHttpConnectionSetPolicyEntries, 22)
MAKE_EXPORT(WinHttpConnectionSetProxyInfo, 23)
MAKE_EXPORT(WinHttpConnectionUpdateIfIndexTable, 24)
MAKE_EXPORT(WinHttpCrackUrl, 25)
MAKE_EXPORT(WinHttpCreateProxyList, 26)
MAKE_EXPORT(WinHttpCreateProxyManager, 27)
MAKE_EXPORT(WinHttpCreateProxyResolver, 28)
MAKE_EXPORT(WinHttpCreateProxyResult, 29)
MAKE_EXPORT(WinHttpCreateUiCompatibleProxyString, 30)
MAKE_EXPORT(WinHttpCreateUrl, 31)
MAKE_EXPORT(WinHttpDetectAutoProxyConfigUrl, 32)
MAKE_EXPORT(WinHttpFreeProxyResult, 33)
MAKE_EXPORT(WinHttpFreeProxyResultEx, 34)
MAKE_EXPORT(WinHttpFreeProxySettings, 35)
MAKE_EXPORT(WinHttpFreeProxySettingsEx, 36)
MAKE_EXPORT(WinHttpFreeQueryConnectionGroupResult, 37)
MAKE_EXPORT(WinHttpGetDefaultProxyConfiguration, 38)
MAKE_EXPORT(WinHttpGetIEProxyConfigForCurrentUser, 39)
MAKE_EXPORT(WinHttpGetProxyForUrl, 40)
MAKE_EXPORT(WinHttpGetProxyForUrlEx, 41)
MAKE_EXPORT(WinHttpGetProxyForUrlEx2, 42)
MAKE_EXPORT(WinHttpGetProxyForUrlHvsi, 43)
MAKE_EXPORT(WinHttpGetProxyResult, 44)
MAKE_EXPORT(WinHttpGetProxyResultEx, 45)
MAKE_EXPORT(WinHttpGetProxySettingsEx, 46)
MAKE_EXPORT(WinHttpGetProxySettingsResultEx, 47)
MAKE_EXPORT(WinHttpGetProxySettingsVersion, 48)
MAKE_EXPORT(WinHttpGetTunnelSocket, 49)
MAKE_EXPORT(WinHttpOpen, 50)
MAKE_EXPORT(WinHttpOpenRequest, 51)
MAKE_EXPORT(WinHttpPacJsWorkerMain, 52)
MAKE_EXPORT(WinHttpProbeConnectivity, 53)
MAKE_EXPORT(WinHttpProtocolCompleteUpgrade, 54)
MAKE_EXPORT(WinHttpProtocolReceive, 55)
MAKE_EXPORT(WinHttpProtocolSend, 56)
MAKE_EXPORT(WinHttpQueryAuthSchemes, 57)
MAKE_EXPORT(WinHttpQueryConnectionGroup, 58)
MAKE_EXPORT(WinHttpQueryDataAvailable, 59)
MAKE_EXPORT(WinHttpQueryHeaders, 60)
MAKE_EXPORT(WinHttpQueryHeadersEx, 61)
MAKE_EXPORT(WinHttpQueryOption, 62)
MAKE_EXPORT(WinHttpReadData, 63)
MAKE_EXPORT(WinHttpReadDataEx, 64)
MAKE_EXPORT(WinHttpReadProxySettings, 65)
MAKE_EXPORT(WinHttpReadProxySettingsHvsi, 66)
MAKE_EXPORT(WinHttpReceiveResponse, 67)
MAKE_EXPORT(WinHttpRefreshProxySettings, 68)
MAKE_EXPORT(WinHttpRegisterProxyChangeNotification, 69)
MAKE_EXPORT(WinHttpResetAutoProxy, 70)
MAKE_EXPORT(WinHttpResolverGetProxyForUrl, 71)
MAKE_EXPORT(WinHttpSaveProxyCredentials, 72)
MAKE_EXPORT(WinHttpSendRequest, 73)
MAKE_EXPORT(WinHttpSetCredentials, 74)
MAKE_EXPORT(WinHttpSetDefaultProxyConfiguration, 75)
MAKE_EXPORT(WinHttpSetOption, 76)
MAKE_EXPORT(WinHttpSetProxySettingsPerUser, 77)
MAKE_EXPORT(WinHttpSetSecureLegacyServersAppCompat, 78)
MAKE_EXPORT(WinHttpSetStatusCallback, 79)
MAKE_EXPORT(WinHttpSetTimeouts, 80)
MAKE_EXPORT(WinHttpTimeFromSystemTime, 81)
MAKE_EXPORT(WinHttpTimeToSystemTime, 82)
MAKE_EXPORT(WinHttpUnregisterProxyChangeNotification, 83)
MAKE_EXPORT(WinHttpWebSocketClose, 84)
MAKE_EXPORT(WinHttpWebSocketCompleteUpgrade, 85)
MAKE_EXPORT(WinHttpWebSocketQueryCloseStatus, 86)
MAKE_EXPORT(WinHttpWebSocketReceive, 87)
MAKE_EXPORT(WinHttpWebSocketSend, 88)
MAKE_EXPORT(WinHttpWebSocketShutdown, 89)
MAKE_EXPORT(WinHttpWriteData, 90)
MAKE_EXPORT(WinHttpWriteProxySettings, 91)

// COM exports (PRIVATE flag)
MAKE_EXPORT_PRIVATE(DllCanUnloadNow, 1)
MAKE_EXPORT_PRIVATE(DllGetClassObject, 2)

#endif // WINHTTP_EXPORTS_H
