; Auto-generated RUNTIME forwarding thunks for winhttp.dll
; Generated by extract_exports.py (runtime mode)
;
; Each function is a simple JMP through a function pointer.
; The function pointers (orig_*) are defined in winhttp_runtime.h
; and initialized by LoadOriginalDLL() at runtime.
;
; Total thunks: 91
; Architecture: x64 only
; Assembler: MASM (ml64.exe)

.data
EXTERNDEF orig_Private1 : QWORD
EXTERNDEF orig_SvchostPushServiceGlobals : QWORD
EXTERNDEF orig_WinHttpAddRequestHeaders : QWORD
EXTERNDEF orig_WinHttpAddRequestHeadersEx : QWORD
EXTERNDEF orig_WinHttpAutoProxySvcMain : QWORD
EXTERNDEF orig_WinHttpCheckPlatform : QWORD
EXTERNDEF orig_WinHttpCloseHandle : QWORD
EXTERNDEF orig_WinHttpConnect : QWORD
EXTERNDEF orig_WinHttpConnectionDeletePolicyEntries : QWORD
EXTERNDEF orig_WinHttpConnectionDeleteProxyInfo : QWORD
EXTERNDEF orig_WinHttpConnectionFreeNameList : QWORD
EXTERNDEF orig_WinHttpConnectionFreeProxyInfo : QWORD
EXTERNDEF orig_WinHttpConnectionFreeProxyList : QWORD
EXTERNDEF orig_WinHttpConnectionGetNameList : QWORD
EXTERNDEF orig_WinHttpConnectionGetProxyInfo : QWORD
EXTERNDEF orig_WinHttpConnectionGetProxyList : QWORD
EXTERNDEF orig_WinHttpConnectionOnlyConvert : QWORD
EXTERNDEF orig_WinHttpConnectionOnlyReceive : QWORD
EXTERNDEF orig_WinHttpConnectionOnlySend : QWORD
EXTERNDEF orig_WinHttpConnectionSetPolicyEntries : QWORD
EXTERNDEF orig_WinHttpConnectionSetProxyInfo : QWORD
EXTERNDEF orig_WinHttpConnectionUpdateIfIndexTable : QWORD
EXTERNDEF orig_WinHttpCrackUrl : QWORD
EXTERNDEF orig_WinHttpCreateProxyList : QWORD
EXTERNDEF orig_WinHttpCreateProxyManager : QWORD
EXTERNDEF orig_WinHttpCreateProxyResolver : QWORD
EXTERNDEF orig_WinHttpCreateProxyResult : QWORD
EXTERNDEF orig_WinHttpCreateUiCompatibleProxyString : QWORD
EXTERNDEF orig_WinHttpCreateUrl : QWORD
EXTERNDEF orig_WinHttpDetectAutoProxyConfigUrl : QWORD
EXTERNDEF orig_WinHttpFreeProxyResult : QWORD
EXTERNDEF orig_WinHttpFreeProxyResultEx : QWORD
EXTERNDEF orig_WinHttpFreeProxySettings : QWORD
EXTERNDEF orig_WinHttpFreeProxySettingsEx : QWORD
EXTERNDEF orig_WinHttpFreeQueryConnectionGroupResult : QWORD
EXTERNDEF orig_WinHttpGetDefaultProxyConfiguration : QWORD
EXTERNDEF orig_WinHttpGetIEProxyConfigForCurrentUser : QWORD
EXTERNDEF orig_WinHttpGetProxyForUrl : QWORD
EXTERNDEF orig_WinHttpGetProxyForUrlEx : QWORD
EXTERNDEF orig_WinHttpGetProxyForUrlEx2 : QWORD
EXTERNDEF orig_WinHttpGetProxyForUrlHvsi : QWORD
EXTERNDEF orig_WinHttpGetProxyResult : QWORD
EXTERNDEF orig_WinHttpGetProxyResultEx : QWORD
EXTERNDEF orig_WinHttpGetProxySettingsEx : QWORD
EXTERNDEF orig_WinHttpGetProxySettingsResultEx : QWORD
EXTERNDEF orig_WinHttpGetProxySettingsVersion : QWORD
EXTERNDEF orig_WinHttpGetTunnelSocket : QWORD
EXTERNDEF orig_WinHttpOpen : QWORD
EXTERNDEF orig_WinHttpOpenRequest : QWORD
EXTERNDEF orig_WinHttpPacJsWorkerMain : QWORD
EXTERNDEF orig_WinHttpProbeConnectivity : QWORD
EXTERNDEF orig_WinHttpProtocolCompleteUpgrade : QWORD
EXTERNDEF orig_WinHttpProtocolReceive : QWORD
EXTERNDEF orig_WinHttpProtocolSend : QWORD
EXTERNDEF orig_WinHttpQueryAuthSchemes : QWORD
EXTERNDEF orig_WinHttpQueryConnectionGroup : QWORD
EXTERNDEF orig_WinHttpQueryDataAvailable : QWORD
EXTERNDEF orig_WinHttpQueryHeaders : QWORD
EXTERNDEF orig_WinHttpQueryHeadersEx : QWORD
EXTERNDEF orig_WinHttpQueryOption : QWORD
EXTERNDEF orig_WinHttpReadData : QWORD
EXTERNDEF orig_WinHttpReadDataEx : QWORD
EXTERNDEF orig_WinHttpReadProxySettings : QWORD
EXTERNDEF orig_WinHttpReadProxySettingsHvsi : QWORD
EXTERNDEF orig_WinHttpReceiveResponse : QWORD
EXTERNDEF orig_WinHttpRefreshProxySettings : QWORD
EXTERNDEF orig_WinHttpRegisterProxyChangeNotification : QWORD
EXTERNDEF orig_WinHttpResetAutoProxy : QWORD
EXTERNDEF orig_WinHttpResolverGetProxyForUrl : QWORD
EXTERNDEF orig_WinHttpSaveProxyCredentials : QWORD
EXTERNDEF orig_WinHttpSendRequest : QWORD
EXTERNDEF orig_WinHttpSetCredentials : QWORD
EXTERNDEF orig_WinHttpSetDefaultProxyConfiguration : QWORD
EXTERNDEF orig_WinHttpSetOption : QWORD
EXTERNDEF orig_WinHttpSetProxySettingsPerUser : QWORD
EXTERNDEF orig_WinHttpSetSecureLegacyServersAppCompat : QWORD
EXTERNDEF orig_WinHttpSetStatusCallback : QWORD
EXTERNDEF orig_WinHttpSetTimeouts : QWORD
EXTERNDEF orig_WinHttpTimeFromSystemTime : QWORD
EXTERNDEF orig_WinHttpTimeToSystemTime : QWORD
EXTERNDEF orig_WinHttpUnregisterProxyChangeNotification : QWORD
EXTERNDEF orig_WinHttpWebSocketClose : QWORD
EXTERNDEF orig_WinHttpWebSocketCompleteUpgrade : QWORD
EXTERNDEF orig_WinHttpWebSocketQueryCloseStatus : QWORD
EXTERNDEF orig_WinHttpWebSocketReceive : QWORD
EXTERNDEF orig_WinHttpWebSocketSend : QWORD
EXTERNDEF orig_WinHttpWebSocketShutdown : QWORD
EXTERNDEF orig_WinHttpWriteData : QWORD
EXTERNDEF orig_WinHttpWriteProxySettings : QWORD
EXTERNDEF orig_DllCanUnloadNow : QWORD
EXTERNDEF orig_DllGetClassObject : QWORD

.code

__proxy_Private1 PROC
    jmp QWORD PTR [orig_Private1]
__proxy_Private1 ENDP

__proxy_SvchostPushServiceGlobals PROC
    jmp QWORD PTR [orig_SvchostPushServiceGlobals]
__proxy_SvchostPushServiceGlobals ENDP

__proxy_WinHttpAddRequestHeaders PROC
    jmp QWORD PTR [orig_WinHttpAddRequestHeaders]
__proxy_WinHttpAddRequestHeaders ENDP

__proxy_WinHttpAddRequestHeadersEx PROC
    jmp QWORD PTR [orig_WinHttpAddRequestHeadersEx]
__proxy_WinHttpAddRequestHeadersEx ENDP

__proxy_WinHttpAutoProxySvcMain PROC
    jmp QWORD PTR [orig_WinHttpAutoProxySvcMain]
__proxy_WinHttpAutoProxySvcMain ENDP

__proxy_WinHttpCheckPlatform PROC
    jmp QWORD PTR [orig_WinHttpCheckPlatform]
__proxy_WinHttpCheckPlatform ENDP

__proxy_WinHttpCloseHandle PROC
    jmp QWORD PTR [orig_WinHttpCloseHandle]
__proxy_WinHttpCloseHandle ENDP

__proxy_WinHttpConnect PROC
    jmp QWORD PTR [orig_WinHttpConnect]
__proxy_WinHttpConnect ENDP

__proxy_WinHttpConnectionDeletePolicyEntries PROC
    jmp QWORD PTR [orig_WinHttpConnectionDeletePolicyEntries]
__proxy_WinHttpConnectionDeletePolicyEntries ENDP

__proxy_WinHttpConnectionDeleteProxyInfo PROC
    jmp QWORD PTR [orig_WinHttpConnectionDeleteProxyInfo]
__proxy_WinHttpConnectionDeleteProxyInfo ENDP

__proxy_WinHttpConnectionFreeNameList PROC
    jmp QWORD PTR [orig_WinHttpConnectionFreeNameList]
__proxy_WinHttpConnectionFreeNameList ENDP

__proxy_WinHttpConnectionFreeProxyInfo PROC
    jmp QWORD PTR [orig_WinHttpConnectionFreeProxyInfo]
__proxy_WinHttpConnectionFreeProxyInfo ENDP

__proxy_WinHttpConnectionFreeProxyList PROC
    jmp QWORD PTR [orig_WinHttpConnectionFreeProxyList]
__proxy_WinHttpConnectionFreeProxyList ENDP

__proxy_WinHttpConnectionGetNameList PROC
    jmp QWORD PTR [orig_WinHttpConnectionGetNameList]
__proxy_WinHttpConnectionGetNameList ENDP

__proxy_WinHttpConnectionGetProxyInfo PROC
    jmp QWORD PTR [orig_WinHttpConnectionGetProxyInfo]
__proxy_WinHttpConnectionGetProxyInfo ENDP

__proxy_WinHttpConnectionGetProxyList PROC
    jmp QWORD PTR [orig_WinHttpConnectionGetProxyList]
__proxy_WinHttpConnectionGetProxyList ENDP

__proxy_WinHttpConnectionOnlyConvert PROC
    jmp QWORD PTR [orig_WinHttpConnectionOnlyConvert]
__proxy_WinHttpConnectionOnlyConvert ENDP

__proxy_WinHttpConnectionOnlyReceive PROC
    jmp QWORD PTR [orig_WinHttpConnectionOnlyReceive]
__proxy_WinHttpConnectionOnlyReceive ENDP

__proxy_WinHttpConnectionOnlySend PROC
    jmp QWORD PTR [orig_WinHttpConnectionOnlySend]
__proxy_WinHttpConnectionOnlySend ENDP

__proxy_WinHttpConnectionSetPolicyEntries PROC
    jmp QWORD PTR [orig_WinHttpConnectionSetPolicyEntries]
__proxy_WinHttpConnectionSetPolicyEntries ENDP

__proxy_WinHttpConnectionSetProxyInfo PROC
    jmp QWORD PTR [orig_WinHttpConnectionSetProxyInfo]
__proxy_WinHttpConnectionSetProxyInfo ENDP

__proxy_WinHttpConnectionUpdateIfIndexTable PROC
    jmp QWORD PTR [orig_WinHttpConnectionUpdateIfIndexTable]
__proxy_WinHttpConnectionUpdateIfIndexTable ENDP

__proxy_WinHttpCrackUrl PROC
    jmp QWORD PTR [orig_WinHttpCrackUrl]
__proxy_WinHttpCrackUrl ENDP

__proxy_WinHttpCreateProxyList PROC
    jmp QWORD PTR [orig_WinHttpCreateProxyList]
__proxy_WinHttpCreateProxyList ENDP

__proxy_WinHttpCreateProxyManager PROC
    jmp QWORD PTR [orig_WinHttpCreateProxyManager]
__proxy_WinHttpCreateProxyManager ENDP

__proxy_WinHttpCreateProxyResolver PROC
    jmp QWORD PTR [orig_WinHttpCreateProxyResolver]
__proxy_WinHttpCreateProxyResolver ENDP

__proxy_WinHttpCreateProxyResult PROC
    jmp QWORD PTR [orig_WinHttpCreateProxyResult]
__proxy_WinHttpCreateProxyResult ENDP

__proxy_WinHttpCreateUiCompatibleProxyString PROC
    jmp QWORD PTR [orig_WinHttpCreateUiCompatibleProxyString]
__proxy_WinHttpCreateUiCompatibleProxyString ENDP

__proxy_WinHttpCreateUrl PROC
    jmp QWORD PTR [orig_WinHttpCreateUrl]
__proxy_WinHttpCreateUrl ENDP

__proxy_WinHttpDetectAutoProxyConfigUrl PROC
    jmp QWORD PTR [orig_WinHttpDetectAutoProxyConfigUrl]
__proxy_WinHttpDetectAutoProxyConfigUrl ENDP

__proxy_WinHttpFreeProxyResult PROC
    jmp QWORD PTR [orig_WinHttpFreeProxyResult]
__proxy_WinHttpFreeProxyResult ENDP

__proxy_WinHttpFreeProxyResultEx PROC
    jmp QWORD PTR [orig_WinHttpFreeProxyResultEx]
__proxy_WinHttpFreeProxyResultEx ENDP

__proxy_WinHttpFreeProxySettings PROC
    jmp QWORD PTR [orig_WinHttpFreeProxySettings]
__proxy_WinHttpFreeProxySettings ENDP

__proxy_WinHttpFreeProxySettingsEx PROC
    jmp QWORD PTR [orig_WinHttpFreeProxySettingsEx]
__proxy_WinHttpFreeProxySettingsEx ENDP

__proxy_WinHttpFreeQueryConnectionGroupResult PROC
    jmp QWORD PTR [orig_WinHttpFreeQueryConnectionGroupResult]
__proxy_WinHttpFreeQueryConnectionGroupResult ENDP

__proxy_WinHttpGetDefaultProxyConfiguration PROC
    jmp QWORD PTR [orig_WinHttpGetDefaultProxyConfiguration]
__proxy_WinHttpGetDefaultProxyConfiguration ENDP

__proxy_WinHttpGetIEProxyConfigForCurrentUser PROC
    jmp QWORD PTR [orig_WinHttpGetIEProxyConfigForCurrentUser]
__proxy_WinHttpGetIEProxyConfigForCurrentUser ENDP

__proxy_WinHttpGetProxyForUrl PROC
    jmp QWORD PTR [orig_WinHttpGetProxyForUrl]
__proxy_WinHttpGetProxyForUrl ENDP

__proxy_WinHttpGetProxyForUrlEx PROC
    jmp QWORD PTR [orig_WinHttpGetProxyForUrlEx]
__proxy_WinHttpGetProxyForUrlEx ENDP

__proxy_WinHttpGetProxyForUrlEx2 PROC
    jmp QWORD PTR [orig_WinHttpGetProxyForUrlEx2]
__proxy_WinHttpGetProxyForUrlEx2 ENDP

__proxy_WinHttpGetProxyForUrlHvsi PROC
    jmp QWORD PTR [orig_WinHttpGetProxyForUrlHvsi]
__proxy_WinHttpGetProxyForUrlHvsi ENDP

__proxy_WinHttpGetProxyResult PROC
    jmp QWORD PTR [orig_WinHttpGetProxyResult]
__proxy_WinHttpGetProxyResult ENDP

__proxy_WinHttpGetProxyResultEx PROC
    jmp QWORD PTR [orig_WinHttpGetProxyResultEx]
__proxy_WinHttpGetProxyResultEx ENDP

__proxy_WinHttpGetProxySettingsEx PROC
    jmp QWORD PTR [orig_WinHttpGetProxySettingsEx]
__proxy_WinHttpGetProxySettingsEx ENDP

__proxy_WinHttpGetProxySettingsResultEx PROC
    jmp QWORD PTR [orig_WinHttpGetProxySettingsResultEx]
__proxy_WinHttpGetProxySettingsResultEx ENDP

__proxy_WinHttpGetProxySettingsVersion PROC
    jmp QWORD PTR [orig_WinHttpGetProxySettingsVersion]
__proxy_WinHttpGetProxySettingsVersion ENDP

__proxy_WinHttpGetTunnelSocket PROC
    jmp QWORD PTR [orig_WinHttpGetTunnelSocket]
__proxy_WinHttpGetTunnelSocket ENDP

__proxy_WinHttpOpen PROC
    jmp QWORD PTR [orig_WinHttpOpen]
__proxy_WinHttpOpen ENDP

__proxy_WinHttpOpenRequest PROC
    jmp QWORD PTR [orig_WinHttpOpenRequest]
__proxy_WinHttpOpenRequest ENDP

__proxy_WinHttpPacJsWorkerMain PROC
    jmp QWORD PTR [orig_WinHttpPacJsWorkerMain]
__proxy_WinHttpPacJsWorkerMain ENDP

__proxy_WinHttpProbeConnectivity PROC
    jmp QWORD PTR [orig_WinHttpProbeConnectivity]
__proxy_WinHttpProbeConnectivity ENDP

__proxy_WinHttpProtocolCompleteUpgrade PROC
    jmp QWORD PTR [orig_WinHttpProtocolCompleteUpgrade]
__proxy_WinHttpProtocolCompleteUpgrade ENDP

__proxy_WinHttpProtocolReceive PROC
    jmp QWORD PTR [orig_WinHttpProtocolReceive]
__proxy_WinHttpProtocolReceive ENDP

__proxy_WinHttpProtocolSend PROC
    jmp QWORD PTR [orig_WinHttpProtocolSend]
__proxy_WinHttpProtocolSend ENDP

__proxy_WinHttpQueryAuthSchemes PROC
    jmp QWORD PTR [orig_WinHttpQueryAuthSchemes]
__proxy_WinHttpQueryAuthSchemes ENDP

__proxy_WinHttpQueryConnectionGroup PROC
    jmp QWORD PTR [orig_WinHttpQueryConnectionGroup]
__proxy_WinHttpQueryConnectionGroup ENDP

__proxy_WinHttpQueryDataAvailable PROC
    jmp QWORD PTR [orig_WinHttpQueryDataAvailable]
__proxy_WinHttpQueryDataAvailable ENDP

__proxy_WinHttpQueryHeaders PROC
    jmp QWORD PTR [orig_WinHttpQueryHeaders]
__proxy_WinHttpQueryHeaders ENDP

__proxy_WinHttpQueryHeadersEx PROC
    jmp QWORD PTR [orig_WinHttpQueryHeadersEx]
__proxy_WinHttpQueryHeadersEx ENDP

__proxy_WinHttpQueryOption PROC
    jmp QWORD PTR [orig_WinHttpQueryOption]
__proxy_WinHttpQueryOption ENDP

__proxy_WinHttpReadData PROC
    jmp QWORD PTR [orig_WinHttpReadData]
__proxy_WinHttpReadData ENDP

__proxy_WinHttpReadDataEx PROC
    jmp QWORD PTR [orig_WinHttpReadDataEx]
__proxy_WinHttpReadDataEx ENDP

__proxy_WinHttpReadProxySettings PROC
    jmp QWORD PTR [orig_WinHttpReadProxySettings]
__proxy_WinHttpReadProxySettings ENDP

__proxy_WinHttpReadProxySettingsHvsi PROC
    jmp QWORD PTR [orig_WinHttpReadProxySettingsHvsi]
__proxy_WinHttpReadProxySettingsHvsi ENDP

__proxy_WinHttpReceiveResponse PROC
    jmp QWORD PTR [orig_WinHttpReceiveResponse]
__proxy_WinHttpReceiveResponse ENDP

__proxy_WinHttpRefreshProxySettings PROC
    jmp QWORD PTR [orig_WinHttpRefreshProxySettings]
__proxy_WinHttpRefreshProxySettings ENDP

__proxy_WinHttpRegisterProxyChangeNotification PROC
    jmp QWORD PTR [orig_WinHttpRegisterProxyChangeNotification]
__proxy_WinHttpRegisterProxyChangeNotification ENDP

__proxy_WinHttpResetAutoProxy PROC
    jmp QWORD PTR [orig_WinHttpResetAutoProxy]
__proxy_WinHttpResetAutoProxy ENDP

__proxy_WinHttpResolverGetProxyForUrl PROC
    jmp QWORD PTR [orig_WinHttpResolverGetProxyForUrl]
__proxy_WinHttpResolverGetProxyForUrl ENDP

__proxy_WinHttpSaveProxyCredentials PROC
    jmp QWORD PTR [orig_WinHttpSaveProxyCredentials]
__proxy_WinHttpSaveProxyCredentials ENDP

__proxy_WinHttpSendRequest PROC
    jmp QWORD PTR [orig_WinHttpSendRequest]
__proxy_WinHttpSendRequest ENDP

__proxy_WinHttpSetCredentials PROC
    jmp QWORD PTR [orig_WinHttpSetCredentials]
__proxy_WinHttpSetCredentials ENDP

__proxy_WinHttpSetDefaultProxyConfiguration PROC
    jmp QWORD PTR [orig_WinHttpSetDefaultProxyConfiguration]
__proxy_WinHttpSetDefaultProxyConfiguration ENDP

__proxy_WinHttpSetOption PROC
    jmp QWORD PTR [orig_WinHttpSetOption]
__proxy_WinHttpSetOption ENDP

__proxy_WinHttpSetProxySettingsPerUser PROC
    jmp QWORD PTR [orig_WinHttpSetProxySettingsPerUser]
__proxy_WinHttpSetProxySettingsPerUser ENDP

__proxy_WinHttpSetSecureLegacyServersAppCompat PROC
    jmp QWORD PTR [orig_WinHttpSetSecureLegacyServersAppCompat]
__proxy_WinHttpSetSecureLegacyServersAppCompat ENDP

__proxy_WinHttpSetStatusCallback PROC
    jmp QWORD PTR [orig_WinHttpSetStatusCallback]
__proxy_WinHttpSetStatusCallback ENDP

__proxy_WinHttpSetTimeouts PROC
    jmp QWORD PTR [orig_WinHttpSetTimeouts]
__proxy_WinHttpSetTimeouts ENDP

__proxy_WinHttpTimeFromSystemTime PROC
    jmp QWORD PTR [orig_WinHttpTimeFromSystemTime]
__proxy_WinHttpTimeFromSystemTime ENDP

__proxy_WinHttpTimeToSystemTime PROC
    jmp QWORD PTR [orig_WinHttpTimeToSystemTime]
__proxy_WinHttpTimeToSystemTime ENDP

__proxy_WinHttpUnregisterProxyChangeNotification PROC
    jmp QWORD PTR [orig_WinHttpUnregisterProxyChangeNotification]
__proxy_WinHttpUnregisterProxyChangeNotification ENDP

__proxy_WinHttpWebSocketClose PROC
    jmp QWORD PTR [orig_WinHttpWebSocketClose]
__proxy_WinHttpWebSocketClose ENDP

__proxy_WinHttpWebSocketCompleteUpgrade PROC
    jmp QWORD PTR [orig_WinHttpWebSocketCompleteUpgrade]
__proxy_WinHttpWebSocketCompleteUpgrade ENDP

__proxy_WinHttpWebSocketQueryCloseStatus PROC
    jmp QWORD PTR [orig_WinHttpWebSocketQueryCloseStatus]
__proxy_WinHttpWebSocketQueryCloseStatus ENDP

__proxy_WinHttpWebSocketReceive PROC
    jmp QWORD PTR [orig_WinHttpWebSocketReceive]
__proxy_WinHttpWebSocketReceive ENDP

__proxy_WinHttpWebSocketSend PROC
    jmp QWORD PTR [orig_WinHttpWebSocketSend]
__proxy_WinHttpWebSocketSend ENDP

__proxy_WinHttpWebSocketShutdown PROC
    jmp QWORD PTR [orig_WinHttpWebSocketShutdown]
__proxy_WinHttpWebSocketShutdown ENDP

__proxy_WinHttpWriteData PROC
    jmp QWORD PTR [orig_WinHttpWriteData]
__proxy_WinHttpWriteData ENDP

__proxy_WinHttpWriteProxySettings PROC
    jmp QWORD PTR [orig_WinHttpWriteProxySettings]
__proxy_WinHttpWriteProxySettings ENDP

__proxy_DllCanUnloadNow PROC
    jmp QWORD PTR [orig_DllCanUnloadNow]
__proxy_DllCanUnloadNow ENDP

__proxy_DllGetClassObject PROC
    jmp QWORD PTR [orig_DllGetClassObject]
__proxy_DllGetClassObject ENDP

END
