; Auto-generated RUNTIME forwarding thunks for wininet.dll
; Generated by extract_exports.py (runtime mode)
;
; Each function is a simple JMP through a function pointer.
; The function pointers (orig_*) are defined in wininet_runtime.h
; and initialized by LoadOriginalDLL() at runtime.
;
; Total thunks: 327
; Architecture: x64 only
; Assembler: MASM (ml64.exe)

.data
EXTERNDEF orig_AppCacheCheckManifest : QWORD
EXTERNDEF orig_AppCacheCloseHandle : QWORD
EXTERNDEF orig_AppCacheCreateAndCommitFile : QWORD
EXTERNDEF orig_AppCacheDeleteGroup : QWORD
EXTERNDEF orig_AppCacheDeleteIEGroup : QWORD
EXTERNDEF orig_AppCacheDuplicateHandle : QWORD
EXTERNDEF orig_AppCacheFinalize : QWORD
EXTERNDEF orig_AppCacheFreeDownloadList : QWORD
EXTERNDEF orig_AppCacheFreeGroupList : QWORD
EXTERNDEF orig_AppCacheFreeIESpace : QWORD
EXTERNDEF orig_AppCacheFreeSpace : QWORD
EXTERNDEF orig_AppCacheGetDownloadList : QWORD
EXTERNDEF orig_AppCacheGetFallbackUrl : QWORD
EXTERNDEF orig_AppCacheGetGroupList : QWORD
EXTERNDEF orig_AppCacheGetIEGroupList : QWORD
EXTERNDEF orig_AppCacheGetInfo : QWORD
EXTERNDEF orig_AppCacheGetManifestUrl : QWORD
EXTERNDEF orig_AppCacheLookup : QWORD
EXTERNDEF orig_CommitUrlCacheEntryA : QWORD
EXTERNDEF orig_CommitUrlCacheEntryBinaryBlob : QWORD
EXTERNDEF orig_CommitUrlCacheEntryW : QWORD
EXTERNDEF orig_CreateMD5SSOHash : QWORD
EXTERNDEF orig_CreateUrlCacheContainerA : QWORD
EXTERNDEF orig_CreateUrlCacheContainerW : QWORD
EXTERNDEF orig_CreateUrlCacheEntryA : QWORD
EXTERNDEF orig_CreateUrlCacheEntryExW : QWORD
EXTERNDEF orig_CreateUrlCacheEntryW : QWORD
EXTERNDEF orig_CreateUrlCacheGroup : QWORD
EXTERNDEF orig_DeleteIE3Cache : QWORD
EXTERNDEF orig_DeleteUrlCacheContainerA : QWORD
EXTERNDEF orig_DeleteUrlCacheContainerW : QWORD
EXTERNDEF orig_DeleteUrlCacheEntry : QWORD
EXTERNDEF orig_DeleteUrlCacheEntryA : QWORD
EXTERNDEF orig_DeleteUrlCacheEntryW : QWORD
EXTERNDEF orig_DeleteUrlCacheGroup : QWORD
EXTERNDEF orig_DeleteWpadCacheForNetworks : QWORD
EXTERNDEF orig_DetectAutoProxyUrl : QWORD
EXTERNDEF orig_DispatchAPICall : QWORD
EXTERNDEF orig_FindCloseUrlCache : QWORD
EXTERNDEF orig_FindFirstUrlCacheContainerA : QWORD
EXTERNDEF orig_FindFirstUrlCacheContainerW : QWORD
EXTERNDEF orig_FindFirstUrlCacheEntryA : QWORD
EXTERNDEF orig_FindFirstUrlCacheEntryExA : QWORD
EXTERNDEF orig_FindFirstUrlCacheEntryExW : QWORD
EXTERNDEF orig_FindFirstUrlCacheEntryW : QWORD
EXTERNDEF orig_FindFirstUrlCacheGroup : QWORD
EXTERNDEF orig_FindNextUrlCacheContainerA : QWORD
EXTERNDEF orig_FindNextUrlCacheContainerW : QWORD
EXTERNDEF orig_FindNextUrlCacheEntryA : QWORD
EXTERNDEF orig_FindNextUrlCacheEntryExA : QWORD
EXTERNDEF orig_FindNextUrlCacheEntryExW : QWORD
EXTERNDEF orig_FindNextUrlCacheEntryW : QWORD
EXTERNDEF orig_FindNextUrlCacheGroup : QWORD
EXTERNDEF orig_ForceNexusLookup : QWORD
EXTERNDEF orig_ForceNexusLookupExW : QWORD
EXTERNDEF orig_FreeUrlCacheSpaceA : QWORD
EXTERNDEF orig_FreeUrlCacheSpaceW : QWORD
EXTERNDEF orig_FtpCommandA : QWORD
EXTERNDEF orig_FtpCommandW : QWORD
EXTERNDEF orig_FtpCreateDirectoryA : QWORD
EXTERNDEF orig_FtpCreateDirectoryW : QWORD
EXTERNDEF orig_FtpDeleteFileA : QWORD
EXTERNDEF orig_FtpDeleteFileW : QWORD
EXTERNDEF orig_FtpFindFirstFileA : QWORD
EXTERNDEF orig_FtpFindFirstFileW : QWORD
EXTERNDEF orig_FtpGetCurrentDirectoryA : QWORD
EXTERNDEF orig_FtpGetCurrentDirectoryW : QWORD
EXTERNDEF orig_FtpGetFileA : QWORD
EXTERNDEF orig_FtpGetFileEx : QWORD
EXTERNDEF orig_FtpGetFileSize : QWORD
EXTERNDEF orig_FtpGetFileW : QWORD
EXTERNDEF orig_FtpOpenFileA : QWORD
EXTERNDEF orig_FtpOpenFileW : QWORD
EXTERNDEF orig_FtpPutFileA : QWORD
EXTERNDEF orig_FtpPutFileEx : QWORD
EXTERNDEF orig_FtpPutFileW : QWORD
EXTERNDEF orig_FtpRemoveDirectoryA : QWORD
EXTERNDEF orig_FtpRemoveDirectoryW : QWORD
EXTERNDEF orig_FtpRenameFileA : QWORD
EXTERNDEF orig_FtpRenameFileW : QWORD
EXTERNDEF orig_FtpSetCurrentDirectoryA : QWORD
EXTERNDEF orig_FtpSetCurrentDirectoryW : QWORD
EXTERNDEF orig_GetProxyDllInfo : QWORD
EXTERNDEF orig_GetUrlCacheConfigInfoA : QWORD
EXTERNDEF orig_GetUrlCacheConfigInfoW : QWORD
EXTERNDEF orig_GetUrlCacheEntryBinaryBlob : QWORD
EXTERNDEF orig_GetUrlCacheEntryInfoA : QWORD
EXTERNDEF orig_GetUrlCacheEntryInfoExA : QWORD
EXTERNDEF orig_GetUrlCacheEntryInfoExW : QWORD
EXTERNDEF orig_GetUrlCacheEntryInfoW : QWORD
EXTERNDEF orig_GetUrlCacheGroupAttributeA : QWORD
EXTERNDEF orig_GetUrlCacheGroupAttributeW : QWORD
EXTERNDEF orig_GetUrlCacheHeaderData : QWORD
EXTERNDEF orig_GopherCreateLocatorA : QWORD
EXTERNDEF orig_GopherCreateLocatorW : QWORD
EXTERNDEF orig_GopherFindFirstFileA : QWORD
EXTERNDEF orig_GopherFindFirstFileW : QWORD
EXTERNDEF orig_GopherGetAttributeA : QWORD
EXTERNDEF orig_GopherGetAttributeW : QWORD
EXTERNDEF orig_GopherGetLocatorTypeA : QWORD
EXTERNDEF orig_GopherGetLocatorTypeW : QWORD
EXTERNDEF orig_GopherOpenFileA : QWORD
EXTERNDEF orig_GopherOpenFileW : QWORD
EXTERNDEF orig_HttpAddRequestHeadersA : QWORD
EXTERNDEF orig_HttpAddRequestHeadersW : QWORD
EXTERNDEF orig_HttpCheckDavCompliance : QWORD
EXTERNDEF orig_HttpCloseDependencyHandle : QWORD
EXTERNDEF orig_HttpDuplicateDependencyHandle : QWORD
EXTERNDEF orig_HttpEndRequestA : QWORD
EXTERNDEF orig_HttpEndRequestW : QWORD
EXTERNDEF orig_HttpGetServerCredentials : QWORD
EXTERNDEF orig_HttpGetTunnelSocket : QWORD
EXTERNDEF orig_HttpIndicatePageLoadComplete : QWORD
EXTERNDEF orig_HttpIsHostHstsEnabled : QWORD
EXTERNDEF orig_HttpOpenDependencyHandle : QWORD
EXTERNDEF orig_HttpOpenRequestA : QWORD
EXTERNDEF orig_HttpOpenRequestW : QWORD
EXTERNDEF orig_HttpPushClose : QWORD
EXTERNDEF orig_HttpPushEnable : QWORD
EXTERNDEF orig_HttpPushWait : QWORD
EXTERNDEF orig_HttpQueryInfoA : QWORD
EXTERNDEF orig_HttpQueryInfoW : QWORD
EXTERNDEF orig_HttpSendRequestA : QWORD
EXTERNDEF orig_HttpSendRequestExA : QWORD
EXTERNDEF orig_HttpSendRequestExW : QWORD
EXTERNDEF orig_HttpSendRequestW : QWORD
EXTERNDEF orig_HttpWebSocketClose : QWORD
EXTERNDEF orig_HttpWebSocketCompleteUpgrade : QWORD
EXTERNDEF orig_HttpWebSocketQueryCloseStatus : QWORD
EXTERNDEF orig_HttpWebSocketReceive : QWORD
EXTERNDEF orig_HttpWebSocketSend : QWORD
EXTERNDEF orig_HttpWebSocketShutdown : QWORD
EXTERNDEF orig_IncrementUrlCacheHeaderData : QWORD
EXTERNDEF orig_InternetAlgIdToStringA : QWORD
EXTERNDEF orig_InternetAlgIdToStringW : QWORD
EXTERNDEF orig_InternetAttemptConnect : QWORD
EXTERNDEF orig_InternetAutodial : QWORD
EXTERNDEF orig_InternetAutodialCallback : QWORD
EXTERNDEF orig_InternetAutodialHangup : QWORD
EXTERNDEF orig_InternetCanonicalizeUrlA : QWORD
EXTERNDEF orig_InternetCanonicalizeUrlW : QWORD
EXTERNDEF orig_InternetCheckConnectionA : QWORD
EXTERNDEF orig_InternetCheckConnectionW : QWORD
EXTERNDEF orig_InternetClearAllPerSiteCookieDecisions : QWORD
EXTERNDEF orig_InternetCloseHandle : QWORD
EXTERNDEF orig_InternetCombineUrlA : QWORD
EXTERNDEF orig_InternetCombineUrlW : QWORD
EXTERNDEF orig_InternetConfirmZoneCrossing : QWORD
EXTERNDEF orig_InternetConfirmZoneCrossingA : QWORD
EXTERNDEF orig_InternetConfirmZoneCrossingW : QWORD
EXTERNDEF orig_InternetConnectA : QWORD
EXTERNDEF orig_InternetConnectW : QWORD
EXTERNDEF orig_InternetConvertUrlFromWireToWideChar : QWORD
EXTERNDEF orig_InternetCrackUrlA : QWORD
EXTERNDEF orig_InternetCrackUrlW : QWORD
EXTERNDEF orig_InternetCreateUrlA : QWORD
EXTERNDEF orig_InternetCreateUrlW : QWORD
EXTERNDEF orig_InternetDial : QWORD
EXTERNDEF orig_InternetDialA : QWORD
EXTERNDEF orig_InternetDialW : QWORD
EXTERNDEF orig_InternetEnumPerSiteCookieDecisionA : QWORD
EXTERNDEF orig_InternetEnumPerSiteCookieDecisionW : QWORD
EXTERNDEF orig_InternetErrorDlg : QWORD
EXTERNDEF orig_InternetFindNextFileA : QWORD
EXTERNDEF orig_InternetFindNextFileW : QWORD
EXTERNDEF orig_InternetFortezzaCommand : QWORD
EXTERNDEF orig_InternetFreeCookies : QWORD
EXTERNDEF orig_InternetFreeProxyInfoList : QWORD
EXTERNDEF orig_InternetGetCertByURL : QWORD
EXTERNDEF orig_InternetGetCertByURLA : QWORD
EXTERNDEF orig_InternetGetConnectedState : QWORD
EXTERNDEF orig_InternetGetConnectedStateEx : QWORD
EXTERNDEF orig_InternetGetConnectedStateExA : QWORD
EXTERNDEF orig_InternetGetConnectedStateExW : QWORD
EXTERNDEF orig_InternetGetCookieA : QWORD
EXTERNDEF orig_InternetGetCookieEx2 : QWORD
EXTERNDEF orig_InternetGetCookieExA : QWORD
EXTERNDEF orig_InternetGetCookieExW : QWORD
EXTERNDEF orig_InternetGetCookieW : QWORD
EXTERNDEF orig_InternetGetLastResponseInfoA : QWORD
EXTERNDEF orig_InternetGetLastResponseInfoW : QWORD
EXTERNDEF orig_InternetGetPerSiteCookieDecisionA : QWORD
EXTERNDEF orig_InternetGetPerSiteCookieDecisionW : QWORD
EXTERNDEF orig_InternetGetProxyForUrl : QWORD
EXTERNDEF orig_InternetGetSecurityInfoByURL : QWORD
EXTERNDEF orig_InternetGetSecurityInfoByURLA : QWORD
EXTERNDEF orig_InternetGetSecurityInfoByURLW : QWORD
EXTERNDEF orig_InternetGoOnline : QWORD
EXTERNDEF orig_InternetGoOnlineA : QWORD
EXTERNDEF orig_InternetGoOnlineW : QWORD
EXTERNDEF orig_InternetHangUp : QWORD
EXTERNDEF orig_InternetInitializeAutoProxyDll : QWORD
EXTERNDEF orig_InternetLockRequestFile : QWORD
EXTERNDEF orig_InternetOpenA : QWORD
EXTERNDEF orig_InternetOpenUrlA : QWORD
EXTERNDEF orig_InternetOpenUrlW : QWORD
EXTERNDEF orig_InternetOpenW : QWORD
EXTERNDEF orig_InternetQueryDataAvailable : QWORD
EXTERNDEF orig_InternetQueryFortezzaStatus : QWORD
EXTERNDEF orig_InternetQueryOptionA : QWORD
EXTERNDEF orig_InternetQueryOptionW : QWORD
EXTERNDEF orig_InternetReadFile : QWORD
EXTERNDEF orig_InternetReadFileExA : QWORD
EXTERNDEF orig_InternetReadFileExW : QWORD
EXTERNDEF orig_InternetSecurityProtocolToStringA : QWORD
EXTERNDEF orig_InternetSecurityProtocolToStringW : QWORD
EXTERNDEF orig_InternetSetCookieA : QWORD
EXTERNDEF orig_InternetSetCookieEx2 : QWORD
EXTERNDEF orig_InternetSetCookieExA : QWORD
EXTERNDEF orig_InternetSetCookieExW : QWORD
EXTERNDEF orig_InternetSetCookieW : QWORD
EXTERNDEF orig_InternetSetDialState : QWORD
EXTERNDEF orig_InternetSetDialStateA : QWORD
EXTERNDEF orig_InternetSetDialStateW : QWORD
EXTERNDEF orig_InternetSetFilePointer : QWORD
EXTERNDEF orig_InternetSetOptionA : QWORD
EXTERNDEF orig_InternetSetOptionExA : QWORD
EXTERNDEF orig_InternetSetOptionExW : QWORD
EXTERNDEF orig_InternetSetOptionW : QWORD
EXTERNDEF orig_InternetSetPerSiteCookieDecisionA : QWORD
EXTERNDEF orig_InternetSetPerSiteCookieDecisionW : QWORD
EXTERNDEF orig_InternetSetSecureLegacyServersAppCompat : QWORD
EXTERNDEF orig_InternetSetStatusCallback : QWORD
EXTERNDEF orig_InternetSetStatusCallbackA : QWORD
EXTERNDEF orig_InternetSetStatusCallbackW : QWORD
EXTERNDEF orig_InternetShowSecurityInfoByURL : QWORD
EXTERNDEF orig_InternetShowSecurityInfoByURLA : QWORD
EXTERNDEF orig_InternetShowSecurityInfoByURLW : QWORD
EXTERNDEF orig_InternetTimeFromSystemTime : QWORD
EXTERNDEF orig_InternetTimeFromSystemTimeA : QWORD
EXTERNDEF orig_InternetTimeFromSystemTimeW : QWORD
EXTERNDEF orig_InternetTimeToSystemTime : QWORD
EXTERNDEF orig_InternetTimeToSystemTimeA : QWORD
EXTERNDEF orig_InternetTimeToSystemTimeW : QWORD
EXTERNDEF orig_InternetUnlockRequestFile : QWORD
EXTERNDEF orig_InternetWriteFile : QWORD
EXTERNDEF orig_InternetWriteFileExA : QWORD
EXTERNDEF orig_InternetWriteFileExW : QWORD
EXTERNDEF orig_IsHostInProxyBypassList : QWORD
EXTERNDEF orig_IsUrlCacheEntryExpiredA : QWORD
EXTERNDEF orig_IsUrlCacheEntryExpiredW : QWORD
EXTERNDEF orig_LoadUrlCacheContent : QWORD
EXTERNDEF orig_ParseX509EncodedCertificateForListBoxEntry : QWORD
EXTERNDEF orig_PrivacyGetZonePreferenceW : QWORD
EXTERNDEF orig_PrivacySetZonePreferenceW : QWORD
EXTERNDEF orig_ReadUrlCacheEntryStream : QWORD
EXTERNDEF orig_ReadUrlCacheEntryStreamEx : QWORD
EXTERNDEF orig_RegisterUrlCacheNotification : QWORD
EXTERNDEF orig_ResumeSuspendedDownload : QWORD
EXTERNDEF orig_RetrieveUrlCacheEntryFileA : QWORD
EXTERNDEF orig_RetrieveUrlCacheEntryFileW : QWORD
EXTERNDEF orig_RetrieveUrlCacheEntryStreamA : QWORD
EXTERNDEF orig_RetrieveUrlCacheEntryStreamW : QWORD
EXTERNDEF orig_RunOnceUrlCache : QWORD
EXTERNDEF orig_SetUrlCacheConfigInfoA : QWORD
EXTERNDEF orig_SetUrlCacheConfigInfoW : QWORD
EXTERNDEF orig_SetUrlCacheEntryGroup : QWORD
EXTERNDEF orig_SetUrlCacheEntryGroupA : QWORD
EXTERNDEF orig_SetUrlCacheEntryGroupW : QWORD
EXTERNDEF orig_SetUrlCacheEntryInfoA : QWORD
EXTERNDEF orig_SetUrlCacheEntryInfoW : QWORD
EXTERNDEF orig_SetUrlCacheGroupAttributeA : QWORD
EXTERNDEF orig_SetUrlCacheGroupAttributeW : QWORD
EXTERNDEF orig_SetUrlCacheHeaderData : QWORD
EXTERNDEF orig_ShowCertificate : QWORD
EXTERNDEF orig_ShowClientAuthCerts : QWORD
EXTERNDEF orig_ShowSecurityInfo : QWORD
EXTERNDEF orig_ShowX509EncodedCertificate : QWORD
EXTERNDEF orig_UnlockUrlCacheEntryFile : QWORD
EXTERNDEF orig_UnlockUrlCacheEntryFileA : QWORD
EXTERNDEF orig_UnlockUrlCacheEntryFileW : QWORD
EXTERNDEF orig_UnlockUrlCacheEntryStream : QWORD
EXTERNDEF orig_UpdateUrlCacheContentPath : QWORD
EXTERNDEF orig_UrlCacheCheckEntriesExist : QWORD
EXTERNDEF orig_UrlCacheCloseEntryHandle : QWORD
EXTERNDEF orig_UrlCacheContainerSetEntryMaximumAge : QWORD
EXTERNDEF orig_UrlCacheCreateContainer : QWORD
EXTERNDEF orig_UrlCacheFindFirstEntry : QWORD
EXTERNDEF orig_UrlCacheFindNextEntry : QWORD
EXTERNDEF orig_UrlCacheFreeEntryInfo : QWORD
EXTERNDEF orig_UrlCacheFreeGlobalSpace : QWORD
EXTERNDEF orig_UrlCacheGetContentPaths : QWORD
EXTERNDEF orig_UrlCacheGetEntryInfo : QWORD
EXTERNDEF orig_UrlCacheGetGlobalCacheSize : QWORD
EXTERNDEF orig_UrlCacheGetGlobalLimit : QWORD
EXTERNDEF orig_UrlCacheReadEntryStream : QWORD
EXTERNDEF orig_UrlCacheReloadSettings : QWORD
EXTERNDEF orig_UrlCacheRetrieveEntryFile : QWORD
EXTERNDEF orig_UrlCacheRetrieveEntryStream : QWORD
EXTERNDEF orig_UrlCacheServer : QWORD
EXTERNDEF orig_UrlCacheSetGlobalLimit : QWORD
EXTERNDEF orig_UrlCacheUpdateEntryExtraData : QWORD
EXTERNDEF orig_UrlZonesDetach : QWORD
EXTERNDEF orig__GetFileExtensionFromUrl : QWORD
EXTERNDEF orig_DllCanUnloadNow : QWORD
EXTERNDEF orig_DllGetClassObject : QWORD
EXTERNDEF orig_DllInstall : QWORD
EXTERNDEF orig_DllRegisterServer : QWORD
EXTERNDEF orig_DllUnregisterServer : QWORD
EXTERNDEF orig___proxy_ord101 : QWORD
EXTERNDEF orig___proxy_ord102 : QWORD
EXTERNDEF orig___proxy_ord103 : QWORD
EXTERNDEF orig___proxy_ord104 : QWORD
EXTERNDEF orig___proxy_ord105 : QWORD
EXTERNDEF orig___proxy_ord108 : QWORD
EXTERNDEF orig___proxy_ord109 : QWORD
EXTERNDEF orig___proxy_ord110 : QWORD
EXTERNDEF orig___proxy_ord111 : QWORD
EXTERNDEF orig___proxy_ord112 : QWORD
EXTERNDEF orig___proxy_ord116 : QWORD
EXTERNDEF orig___proxy_ord117 : QWORD
EXTERNDEF orig___proxy_ord118 : QWORD
EXTERNDEF orig___proxy_ord120 : QWORD
EXTERNDEF orig___proxy_ord121 : QWORD
EXTERNDEF orig___proxy_ord122 : QWORD
EXTERNDEF orig___proxy_ord123 : QWORD
EXTERNDEF orig___proxy_ord346 : QWORD
EXTERNDEF orig___proxy_ord401 : QWORD
EXTERNDEF orig___proxy_ord402 : QWORD
EXTERNDEF orig___proxy_ord403 : QWORD
EXTERNDEF orig___proxy_ord410 : QWORD
EXTERNDEF orig___proxy_ord411 : QWORD
EXTERNDEF orig___proxy_ord413 : QWORD
EXTERNDEF orig___proxy_ord420 : QWORD
EXTERNDEF orig___proxy_ord421 : QWORD
EXTERNDEF orig___proxy_ord422 : QWORD
EXTERNDEF orig___proxy_ord423 : QWORD

.code

__proxy_AppCacheCheckManifest PROC
    jmp QWORD PTR [orig_AppCacheCheckManifest]
__proxy_AppCacheCheckManifest ENDP

__proxy_AppCacheCloseHandle PROC
    jmp QWORD PTR [orig_AppCacheCloseHandle]
__proxy_AppCacheCloseHandle ENDP

__proxy_AppCacheCreateAndCommitFile PROC
    jmp QWORD PTR [orig_AppCacheCreateAndCommitFile]
__proxy_AppCacheCreateAndCommitFile ENDP

__proxy_AppCacheDeleteGroup PROC
    jmp QWORD PTR [orig_AppCacheDeleteGroup]
__proxy_AppCacheDeleteGroup ENDP

__proxy_AppCacheDeleteIEGroup PROC
    jmp QWORD PTR [orig_AppCacheDeleteIEGroup]
__proxy_AppCacheDeleteIEGroup ENDP

__proxy_AppCacheDuplicateHandle PROC
    jmp QWORD PTR [orig_AppCacheDuplicateHandle]
__proxy_AppCacheDuplicateHandle ENDP

__proxy_AppCacheFinalize PROC
    jmp QWORD PTR [orig_AppCacheFinalize]
__proxy_AppCacheFinalize ENDP

__proxy_AppCacheFreeDownloadList PROC
    jmp QWORD PTR [orig_AppCacheFreeDownloadList]
__proxy_AppCacheFreeDownloadList ENDP

__proxy_AppCacheFreeGroupList PROC
    jmp QWORD PTR [orig_AppCacheFreeGroupList]
__proxy_AppCacheFreeGroupList ENDP

__proxy_AppCacheFreeIESpace PROC
    jmp QWORD PTR [orig_AppCacheFreeIESpace]
__proxy_AppCacheFreeIESpace ENDP

__proxy_AppCacheFreeSpace PROC
    jmp QWORD PTR [orig_AppCacheFreeSpace]
__proxy_AppCacheFreeSpace ENDP

__proxy_AppCacheGetDownloadList PROC
    jmp QWORD PTR [orig_AppCacheGetDownloadList]
__proxy_AppCacheGetDownloadList ENDP

__proxy_AppCacheGetFallbackUrl PROC
    jmp QWORD PTR [orig_AppCacheGetFallbackUrl]
__proxy_AppCacheGetFallbackUrl ENDP

__proxy_AppCacheGetGroupList PROC
    jmp QWORD PTR [orig_AppCacheGetGroupList]
__proxy_AppCacheGetGroupList ENDP

__proxy_AppCacheGetIEGroupList PROC
    jmp QWORD PTR [orig_AppCacheGetIEGroupList]
__proxy_AppCacheGetIEGroupList ENDP

__proxy_AppCacheGetInfo PROC
    jmp QWORD PTR [orig_AppCacheGetInfo]
__proxy_AppCacheGetInfo ENDP

__proxy_AppCacheGetManifestUrl PROC
    jmp QWORD PTR [orig_AppCacheGetManifestUrl]
__proxy_AppCacheGetManifestUrl ENDP

__proxy_AppCacheLookup PROC
    jmp QWORD PTR [orig_AppCacheLookup]
__proxy_AppCacheLookup ENDP

__proxy_CommitUrlCacheEntryA PROC
    jmp QWORD PTR [orig_CommitUrlCacheEntryA]
__proxy_CommitUrlCacheEntryA ENDP

__proxy_CommitUrlCacheEntryBinaryBlob PROC
    jmp QWORD PTR [orig_CommitUrlCacheEntryBinaryBlob]
__proxy_CommitUrlCacheEntryBinaryBlob ENDP

__proxy_CommitUrlCacheEntryW PROC
    jmp QWORD PTR [orig_CommitUrlCacheEntryW]
__proxy_CommitUrlCacheEntryW ENDP

__proxy_CreateMD5SSOHash PROC
    jmp QWORD PTR [orig_CreateMD5SSOHash]
__proxy_CreateMD5SSOHash ENDP

__proxy_CreateUrlCacheContainerA PROC
    jmp QWORD PTR [orig_CreateUrlCacheContainerA]
__proxy_CreateUrlCacheContainerA ENDP

__proxy_CreateUrlCacheContainerW PROC
    jmp QWORD PTR [orig_CreateUrlCacheContainerW]
__proxy_CreateUrlCacheContainerW ENDP

__proxy_CreateUrlCacheEntryA PROC
    jmp QWORD PTR [orig_CreateUrlCacheEntryA]
__proxy_CreateUrlCacheEntryA ENDP

__proxy_CreateUrlCacheEntryExW PROC
    jmp QWORD PTR [orig_CreateUrlCacheEntryExW]
__proxy_CreateUrlCacheEntryExW ENDP

__proxy_CreateUrlCacheEntryW PROC
    jmp QWORD PTR [orig_CreateUrlCacheEntryW]
__proxy_CreateUrlCacheEntryW ENDP

__proxy_CreateUrlCacheGroup PROC
    jmp QWORD PTR [orig_CreateUrlCacheGroup]
__proxy_CreateUrlCacheGroup ENDP

__proxy_DeleteIE3Cache PROC
    jmp QWORD PTR [orig_DeleteIE3Cache]
__proxy_DeleteIE3Cache ENDP

__proxy_DeleteUrlCacheContainerA PROC
    jmp QWORD PTR [orig_DeleteUrlCacheContainerA]
__proxy_DeleteUrlCacheContainerA ENDP

__proxy_DeleteUrlCacheContainerW PROC
    jmp QWORD PTR [orig_DeleteUrlCacheContainerW]
__proxy_DeleteUrlCacheContainerW ENDP

__proxy_DeleteUrlCacheEntry PROC
    jmp QWORD PTR [orig_DeleteUrlCacheEntry]
__proxy_DeleteUrlCacheEntry ENDP

__proxy_DeleteUrlCacheEntryA PROC
    jmp QWORD PTR [orig_DeleteUrlCacheEntryA]
__proxy_DeleteUrlCacheEntryA ENDP

__proxy_DeleteUrlCacheEntryW PROC
    jmp QWORD PTR [orig_DeleteUrlCacheEntryW]
__proxy_DeleteUrlCacheEntryW ENDP

__proxy_DeleteUrlCacheGroup PROC
    jmp QWORD PTR [orig_DeleteUrlCacheGroup]
__proxy_DeleteUrlCacheGroup ENDP

__proxy_DeleteWpadCacheForNetworks PROC
    jmp QWORD PTR [orig_DeleteWpadCacheForNetworks]
__proxy_DeleteWpadCacheForNetworks ENDP

__proxy_DetectAutoProxyUrl PROC
    jmp QWORD PTR [orig_DetectAutoProxyUrl]
__proxy_DetectAutoProxyUrl ENDP

__proxy_DispatchAPICall PROC
    jmp QWORD PTR [orig_DispatchAPICall]
__proxy_DispatchAPICall ENDP

__proxy_FindCloseUrlCache PROC
    jmp QWORD PTR [orig_FindCloseUrlCache]
__proxy_FindCloseUrlCache ENDP

__proxy_FindFirstUrlCacheContainerA PROC
    jmp QWORD PTR [orig_FindFirstUrlCacheContainerA]
__proxy_FindFirstUrlCacheContainerA ENDP

__proxy_FindFirstUrlCacheContainerW PROC
    jmp QWORD PTR [orig_FindFirstUrlCacheContainerW]
__proxy_FindFirstUrlCacheContainerW ENDP

__proxy_FindFirstUrlCacheEntryA PROC
    jmp QWORD PTR [orig_FindFirstUrlCacheEntryA]
__proxy_FindFirstUrlCacheEntryA ENDP

__proxy_FindFirstUrlCacheEntryExA PROC
    jmp QWORD PTR [orig_FindFirstUrlCacheEntryExA]
__proxy_FindFirstUrlCacheEntryExA ENDP

__proxy_FindFirstUrlCacheEntryExW PROC
    jmp QWORD PTR [orig_FindFirstUrlCacheEntryExW]
__proxy_FindFirstUrlCacheEntryExW ENDP

__proxy_FindFirstUrlCacheEntryW PROC
    jmp QWORD PTR [orig_FindFirstUrlCacheEntryW]
__proxy_FindFirstUrlCacheEntryW ENDP

__proxy_FindFirstUrlCacheGroup PROC
    jmp QWORD PTR [orig_FindFirstUrlCacheGroup]
__proxy_FindFirstUrlCacheGroup ENDP

__proxy_FindNextUrlCacheContainerA PROC
    jmp QWORD PTR [orig_FindNextUrlCacheContainerA]
__proxy_FindNextUrlCacheContainerA ENDP

__proxy_FindNextUrlCacheContainerW PROC
    jmp QWORD PTR [orig_FindNextUrlCacheContainerW]
__proxy_FindNextUrlCacheContainerW ENDP

__proxy_FindNextUrlCacheEntryA PROC
    jmp QWORD PTR [orig_FindNextUrlCacheEntryA]
__proxy_FindNextUrlCacheEntryA ENDP

__proxy_FindNextUrlCacheEntryExA PROC
    jmp QWORD PTR [orig_FindNextUrlCacheEntryExA]
__proxy_FindNextUrlCacheEntryExA ENDP

__proxy_FindNextUrlCacheEntryExW PROC
    jmp QWORD PTR [orig_FindNextUrlCacheEntryExW]
__proxy_FindNextUrlCacheEntryExW ENDP

__proxy_FindNextUrlCacheEntryW PROC
    jmp QWORD PTR [orig_FindNextUrlCacheEntryW]
__proxy_FindNextUrlCacheEntryW ENDP

__proxy_FindNextUrlCacheGroup PROC
    jmp QWORD PTR [orig_FindNextUrlCacheGroup]
__proxy_FindNextUrlCacheGroup ENDP

__proxy_ForceNexusLookup PROC
    jmp QWORD PTR [orig_ForceNexusLookup]
__proxy_ForceNexusLookup ENDP

__proxy_ForceNexusLookupExW PROC
    jmp QWORD PTR [orig_ForceNexusLookupExW]
__proxy_ForceNexusLookupExW ENDP

__proxy_FreeUrlCacheSpaceA PROC
    jmp QWORD PTR [orig_FreeUrlCacheSpaceA]
__proxy_FreeUrlCacheSpaceA ENDP

__proxy_FreeUrlCacheSpaceW PROC
    jmp QWORD PTR [orig_FreeUrlCacheSpaceW]
__proxy_FreeUrlCacheSpaceW ENDP

__proxy_FtpCommandA PROC
    jmp QWORD PTR [orig_FtpCommandA]
__proxy_FtpCommandA ENDP

__proxy_FtpCommandW PROC
    jmp QWORD PTR [orig_FtpCommandW]
__proxy_FtpCommandW ENDP

__proxy_FtpCreateDirectoryA PROC
    jmp QWORD PTR [orig_FtpCreateDirectoryA]
__proxy_FtpCreateDirectoryA ENDP

__proxy_FtpCreateDirectoryW PROC
    jmp QWORD PTR [orig_FtpCreateDirectoryW]
__proxy_FtpCreateDirectoryW ENDP

__proxy_FtpDeleteFileA PROC
    jmp QWORD PTR [orig_FtpDeleteFileA]
__proxy_FtpDeleteFileA ENDP

__proxy_FtpDeleteFileW PROC
    jmp QWORD PTR [orig_FtpDeleteFileW]
__proxy_FtpDeleteFileW ENDP

__proxy_FtpFindFirstFileA PROC
    jmp QWORD PTR [orig_FtpFindFirstFileA]
__proxy_FtpFindFirstFileA ENDP

__proxy_FtpFindFirstFileW PROC
    jmp QWORD PTR [orig_FtpFindFirstFileW]
__proxy_FtpFindFirstFileW ENDP

__proxy_FtpGetCurrentDirectoryA PROC
    jmp QWORD PTR [orig_FtpGetCurrentDirectoryA]
__proxy_FtpGetCurrentDirectoryA ENDP

__proxy_FtpGetCurrentDirectoryW PROC
    jmp QWORD PTR [orig_FtpGetCurrentDirectoryW]
__proxy_FtpGetCurrentDirectoryW ENDP

__proxy_FtpGetFileA PROC
    jmp QWORD PTR [orig_FtpGetFileA]
__proxy_FtpGetFileA ENDP

__proxy_FtpGetFileEx PROC
    jmp QWORD PTR [orig_FtpGetFileEx]
__proxy_FtpGetFileEx ENDP

__proxy_FtpGetFileSize PROC
    jmp QWORD PTR [orig_FtpGetFileSize]
__proxy_FtpGetFileSize ENDP

__proxy_FtpGetFileW PROC
    jmp QWORD PTR [orig_FtpGetFileW]
__proxy_FtpGetFileW ENDP

__proxy_FtpOpenFileA PROC
    jmp QWORD PTR [orig_FtpOpenFileA]
__proxy_FtpOpenFileA ENDP

__proxy_FtpOpenFileW PROC
    jmp QWORD PTR [orig_FtpOpenFileW]
__proxy_FtpOpenFileW ENDP

__proxy_FtpPutFileA PROC
    jmp QWORD PTR [orig_FtpPutFileA]
__proxy_FtpPutFileA ENDP

__proxy_FtpPutFileEx PROC
    jmp QWORD PTR [orig_FtpPutFileEx]
__proxy_FtpPutFileEx ENDP

__proxy_FtpPutFileW PROC
    jmp QWORD PTR [orig_FtpPutFileW]
__proxy_FtpPutFileW ENDP

__proxy_FtpRemoveDirectoryA PROC
    jmp QWORD PTR [orig_FtpRemoveDirectoryA]
__proxy_FtpRemoveDirectoryA ENDP

__proxy_FtpRemoveDirectoryW PROC
    jmp QWORD PTR [orig_FtpRemoveDirectoryW]
__proxy_FtpRemoveDirectoryW ENDP

__proxy_FtpRenameFileA PROC
    jmp QWORD PTR [orig_FtpRenameFileA]
__proxy_FtpRenameFileA ENDP

__proxy_FtpRenameFileW PROC
    jmp QWORD PTR [orig_FtpRenameFileW]
__proxy_FtpRenameFileW ENDP

__proxy_FtpSetCurrentDirectoryA PROC
    jmp QWORD PTR [orig_FtpSetCurrentDirectoryA]
__proxy_FtpSetCurrentDirectoryA ENDP

__proxy_FtpSetCurrentDirectoryW PROC
    jmp QWORD PTR [orig_FtpSetCurrentDirectoryW]
__proxy_FtpSetCurrentDirectoryW ENDP

__proxy_GetProxyDllInfo PROC
    jmp QWORD PTR [orig_GetProxyDllInfo]
__proxy_GetProxyDllInfo ENDP

__proxy_GetUrlCacheConfigInfoA PROC
    jmp QWORD PTR [orig_GetUrlCacheConfigInfoA]
__proxy_GetUrlCacheConfigInfoA ENDP

__proxy_GetUrlCacheConfigInfoW PROC
    jmp QWORD PTR [orig_GetUrlCacheConfigInfoW]
__proxy_GetUrlCacheConfigInfoW ENDP

__proxy_GetUrlCacheEntryBinaryBlob PROC
    jmp QWORD PTR [orig_GetUrlCacheEntryBinaryBlob]
__proxy_GetUrlCacheEntryBinaryBlob ENDP

__proxy_GetUrlCacheEntryInfoA PROC
    jmp QWORD PTR [orig_GetUrlCacheEntryInfoA]
__proxy_GetUrlCacheEntryInfoA ENDP

__proxy_GetUrlCacheEntryInfoExA PROC
    jmp QWORD PTR [orig_GetUrlCacheEntryInfoExA]
__proxy_GetUrlCacheEntryInfoExA ENDP

__proxy_GetUrlCacheEntryInfoExW PROC
    jmp QWORD PTR [orig_GetUrlCacheEntryInfoExW]
__proxy_GetUrlCacheEntryInfoExW ENDP

__proxy_GetUrlCacheEntryInfoW PROC
    jmp QWORD PTR [orig_GetUrlCacheEntryInfoW]
__proxy_GetUrlCacheEntryInfoW ENDP

__proxy_GetUrlCacheGroupAttributeA PROC
    jmp QWORD PTR [orig_GetUrlCacheGroupAttributeA]
__proxy_GetUrlCacheGroupAttributeA ENDP

__proxy_GetUrlCacheGroupAttributeW PROC
    jmp QWORD PTR [orig_GetUrlCacheGroupAttributeW]
__proxy_GetUrlCacheGroupAttributeW ENDP

__proxy_GetUrlCacheHeaderData PROC
    jmp QWORD PTR [orig_GetUrlCacheHeaderData]
__proxy_GetUrlCacheHeaderData ENDP

__proxy_GopherCreateLocatorA PROC
    jmp QWORD PTR [orig_GopherCreateLocatorA]
__proxy_GopherCreateLocatorA ENDP

__proxy_GopherCreateLocatorW PROC
    jmp QWORD PTR [orig_GopherCreateLocatorW]
__proxy_GopherCreateLocatorW ENDP

__proxy_GopherFindFirstFileA PROC
    jmp QWORD PTR [orig_GopherFindFirstFileA]
__proxy_GopherFindFirstFileA ENDP

__proxy_GopherFindFirstFileW PROC
    jmp QWORD PTR [orig_GopherFindFirstFileW]
__proxy_GopherFindFirstFileW ENDP

__proxy_GopherGetAttributeA PROC
    jmp QWORD PTR [orig_GopherGetAttributeA]
__proxy_GopherGetAttributeA ENDP

__proxy_GopherGetAttributeW PROC
    jmp QWORD PTR [orig_GopherGetAttributeW]
__proxy_GopherGetAttributeW ENDP

__proxy_GopherGetLocatorTypeA PROC
    jmp QWORD PTR [orig_GopherGetLocatorTypeA]
__proxy_GopherGetLocatorTypeA ENDP

__proxy_GopherGetLocatorTypeW PROC
    jmp QWORD PTR [orig_GopherGetLocatorTypeW]
__proxy_GopherGetLocatorTypeW ENDP

__proxy_GopherOpenFileA PROC
    jmp QWORD PTR [orig_GopherOpenFileA]
__proxy_GopherOpenFileA ENDP

__proxy_GopherOpenFileW PROC
    jmp QWORD PTR [orig_GopherOpenFileW]
__proxy_GopherOpenFileW ENDP

__proxy_HttpAddRequestHeadersA PROC
    jmp QWORD PTR [orig_HttpAddRequestHeadersA]
__proxy_HttpAddRequestHeadersA ENDP

__proxy_HttpAddRequestHeadersW PROC
    jmp QWORD PTR [orig_HttpAddRequestHeadersW]
__proxy_HttpAddRequestHeadersW ENDP

__proxy_HttpCheckDavCompliance PROC
    jmp QWORD PTR [orig_HttpCheckDavCompliance]
__proxy_HttpCheckDavCompliance ENDP

__proxy_HttpCloseDependencyHandle PROC
    jmp QWORD PTR [orig_HttpCloseDependencyHandle]
__proxy_HttpCloseDependencyHandle ENDP

__proxy_HttpDuplicateDependencyHandle PROC
    jmp QWORD PTR [orig_HttpDuplicateDependencyHandle]
__proxy_HttpDuplicateDependencyHandle ENDP

__proxy_HttpEndRequestA PROC
    jmp QWORD PTR [orig_HttpEndRequestA]
__proxy_HttpEndRequestA ENDP

__proxy_HttpEndRequestW PROC
    jmp QWORD PTR [orig_HttpEndRequestW]
__proxy_HttpEndRequestW ENDP

__proxy_HttpGetServerCredentials PROC
    jmp QWORD PTR [orig_HttpGetServerCredentials]
__proxy_HttpGetServerCredentials ENDP

__proxy_HttpGetTunnelSocket PROC
    jmp QWORD PTR [orig_HttpGetTunnelSocket]
__proxy_HttpGetTunnelSocket ENDP

__proxy_HttpIndicatePageLoadComplete PROC
    jmp QWORD PTR [orig_HttpIndicatePageLoadComplete]
__proxy_HttpIndicatePageLoadComplete ENDP

__proxy_HttpIsHostHstsEnabled PROC
    jmp QWORD PTR [orig_HttpIsHostHstsEnabled]
__proxy_HttpIsHostHstsEnabled ENDP

__proxy_HttpOpenDependencyHandle PROC
    jmp QWORD PTR [orig_HttpOpenDependencyHandle]
__proxy_HttpOpenDependencyHandle ENDP

__proxy_HttpOpenRequestA PROC
    jmp QWORD PTR [orig_HttpOpenRequestA]
__proxy_HttpOpenRequestA ENDP

__proxy_HttpOpenRequestW PROC
    jmp QWORD PTR [orig_HttpOpenRequestW]
__proxy_HttpOpenRequestW ENDP

__proxy_HttpPushClose PROC
    jmp QWORD PTR [orig_HttpPushClose]
__proxy_HttpPushClose ENDP

__proxy_HttpPushEnable PROC
    jmp QWORD PTR [orig_HttpPushEnable]
__proxy_HttpPushEnable ENDP

__proxy_HttpPushWait PROC
    jmp QWORD PTR [orig_HttpPushWait]
__proxy_HttpPushWait ENDP

__proxy_HttpQueryInfoA PROC
    jmp QWORD PTR [orig_HttpQueryInfoA]
__proxy_HttpQueryInfoA ENDP

__proxy_HttpQueryInfoW PROC
    jmp QWORD PTR [orig_HttpQueryInfoW]
__proxy_HttpQueryInfoW ENDP

__proxy_HttpSendRequestA PROC
    jmp QWORD PTR [orig_HttpSendRequestA]
__proxy_HttpSendRequestA ENDP

__proxy_HttpSendRequestExA PROC
    jmp QWORD PTR [orig_HttpSendRequestExA]
__proxy_HttpSendRequestExA ENDP

__proxy_HttpSendRequestExW PROC
    jmp QWORD PTR [orig_HttpSendRequestExW]
__proxy_HttpSendRequestExW ENDP

__proxy_HttpSendRequestW PROC
    jmp QWORD PTR [orig_HttpSendRequestW]
__proxy_HttpSendRequestW ENDP

__proxy_HttpWebSocketClose PROC
    jmp QWORD PTR [orig_HttpWebSocketClose]
__proxy_HttpWebSocketClose ENDP

__proxy_HttpWebSocketCompleteUpgrade PROC
    jmp QWORD PTR [orig_HttpWebSocketCompleteUpgrade]
__proxy_HttpWebSocketCompleteUpgrade ENDP

__proxy_HttpWebSocketQueryCloseStatus PROC
    jmp QWORD PTR [orig_HttpWebSocketQueryCloseStatus]
__proxy_HttpWebSocketQueryCloseStatus ENDP

__proxy_HttpWebSocketReceive PROC
    jmp QWORD PTR [orig_HttpWebSocketReceive]
__proxy_HttpWebSocketReceive ENDP

__proxy_HttpWebSocketSend PROC
    jmp QWORD PTR [orig_HttpWebSocketSend]
__proxy_HttpWebSocketSend ENDP

__proxy_HttpWebSocketShutdown PROC
    jmp QWORD PTR [orig_HttpWebSocketShutdown]
__proxy_HttpWebSocketShutdown ENDP

__proxy_IncrementUrlCacheHeaderData PROC
    jmp QWORD PTR [orig_IncrementUrlCacheHeaderData]
__proxy_IncrementUrlCacheHeaderData ENDP

__proxy_InternetAlgIdToStringA PROC
    jmp QWORD PTR [orig_InternetAlgIdToStringA]
__proxy_InternetAlgIdToStringA ENDP

__proxy_InternetAlgIdToStringW PROC
    jmp QWORD PTR [orig_InternetAlgIdToStringW]
__proxy_InternetAlgIdToStringW ENDP

__proxy_InternetAttemptConnect PROC
    jmp QWORD PTR [orig_InternetAttemptConnect]
__proxy_InternetAttemptConnect ENDP

__proxy_InternetAutodial PROC
    jmp QWORD PTR [orig_InternetAutodial]
__proxy_InternetAutodial ENDP

__proxy_InternetAutodialCallback PROC
    jmp QWORD PTR [orig_InternetAutodialCallback]
__proxy_InternetAutodialCallback ENDP

__proxy_InternetAutodialHangup PROC
    jmp QWORD PTR [orig_InternetAutodialHangup]
__proxy_InternetAutodialHangup ENDP

__proxy_InternetCanonicalizeUrlA PROC
    jmp QWORD PTR [orig_InternetCanonicalizeUrlA]
__proxy_InternetCanonicalizeUrlA ENDP

__proxy_InternetCanonicalizeUrlW PROC
    jmp QWORD PTR [orig_InternetCanonicalizeUrlW]
__proxy_InternetCanonicalizeUrlW ENDP

__proxy_InternetCheckConnectionA PROC
    jmp QWORD PTR [orig_InternetCheckConnectionA]
__proxy_InternetCheckConnectionA ENDP

__proxy_InternetCheckConnectionW PROC
    jmp QWORD PTR [orig_InternetCheckConnectionW]
__proxy_InternetCheckConnectionW ENDP

__proxy_InternetClearAllPerSiteCookieDecisions PROC
    jmp QWORD PTR [orig_InternetClearAllPerSiteCookieDecisions]
__proxy_InternetClearAllPerSiteCookieDecisions ENDP

__proxy_InternetCloseHandle PROC
    jmp QWORD PTR [orig_InternetCloseHandle]
__proxy_InternetCloseHandle ENDP

__proxy_InternetCombineUrlA PROC
    jmp QWORD PTR [orig_InternetCombineUrlA]
__proxy_InternetCombineUrlA ENDP

__proxy_InternetCombineUrlW PROC
    jmp QWORD PTR [orig_InternetCombineUrlW]
__proxy_InternetCombineUrlW ENDP

__proxy_InternetConfirmZoneCrossing PROC
    jmp QWORD PTR [orig_InternetConfirmZoneCrossing]
__proxy_InternetConfirmZoneCrossing ENDP

__proxy_InternetConfirmZoneCrossingA PROC
    jmp QWORD PTR [orig_InternetConfirmZoneCrossingA]
__proxy_InternetConfirmZoneCrossingA ENDP

__proxy_InternetConfirmZoneCrossingW PROC
    jmp QWORD PTR [orig_InternetConfirmZoneCrossingW]
__proxy_InternetConfirmZoneCrossingW ENDP

__proxy_InternetConnectA PROC
    jmp QWORD PTR [orig_InternetConnectA]
__proxy_InternetConnectA ENDP

__proxy_InternetConnectW PROC
    jmp QWORD PTR [orig_InternetConnectW]
__proxy_InternetConnectW ENDP

__proxy_InternetConvertUrlFromWireToWideChar PROC
    jmp QWORD PTR [orig_InternetConvertUrlFromWireToWideChar]
__proxy_InternetConvertUrlFromWireToWideChar ENDP

__proxy_InternetCrackUrlA PROC
    jmp QWORD PTR [orig_InternetCrackUrlA]
__proxy_InternetCrackUrlA ENDP

__proxy_InternetCrackUrlW PROC
    jmp QWORD PTR [orig_InternetCrackUrlW]
__proxy_InternetCrackUrlW ENDP

__proxy_InternetCreateUrlA PROC
    jmp QWORD PTR [orig_InternetCreateUrlA]
__proxy_InternetCreateUrlA ENDP

__proxy_InternetCreateUrlW PROC
    jmp QWORD PTR [orig_InternetCreateUrlW]
__proxy_InternetCreateUrlW ENDP

__proxy_InternetDial PROC
    jmp QWORD PTR [orig_InternetDial]
__proxy_InternetDial ENDP

__proxy_InternetDialA PROC
    jmp QWORD PTR [orig_InternetDialA]
__proxy_InternetDialA ENDP

__proxy_InternetDialW PROC
    jmp QWORD PTR [orig_InternetDialW]
__proxy_InternetDialW ENDP

__proxy_InternetEnumPerSiteCookieDecisionA PROC
    jmp QWORD PTR [orig_InternetEnumPerSiteCookieDecisionA]
__proxy_InternetEnumPerSiteCookieDecisionA ENDP

__proxy_InternetEnumPerSiteCookieDecisionW PROC
    jmp QWORD PTR [orig_InternetEnumPerSiteCookieDecisionW]
__proxy_InternetEnumPerSiteCookieDecisionW ENDP

__proxy_InternetErrorDlg PROC
    jmp QWORD PTR [orig_InternetErrorDlg]
__proxy_InternetErrorDlg ENDP

__proxy_InternetFindNextFileA PROC
    jmp QWORD PTR [orig_InternetFindNextFileA]
__proxy_InternetFindNextFileA ENDP

__proxy_InternetFindNextFileW PROC
    jmp QWORD PTR [orig_InternetFindNextFileW]
__proxy_InternetFindNextFileW ENDP

__proxy_InternetFortezzaCommand PROC
    jmp QWORD PTR [orig_InternetFortezzaCommand]
__proxy_InternetFortezzaCommand ENDP

__proxy_InternetFreeCookies PROC
    jmp QWORD PTR [orig_InternetFreeCookies]
__proxy_InternetFreeCookies ENDP

__proxy_InternetFreeProxyInfoList PROC
    jmp QWORD PTR [orig_InternetFreeProxyInfoList]
__proxy_InternetFreeProxyInfoList ENDP

__proxy_InternetGetCertByURL PROC
    jmp QWORD PTR [orig_InternetGetCertByURL]
__proxy_InternetGetCertByURL ENDP

__proxy_InternetGetCertByURLA PROC
    jmp QWORD PTR [orig_InternetGetCertByURLA]
__proxy_InternetGetCertByURLA ENDP

__proxy_InternetGetConnectedState PROC
    jmp QWORD PTR [orig_InternetGetConnectedState]
__proxy_InternetGetConnectedState ENDP

__proxy_InternetGetConnectedStateEx PROC
    jmp QWORD PTR [orig_InternetGetConnectedStateEx]
__proxy_InternetGetConnectedStateEx ENDP

__proxy_InternetGetConnectedStateExA PROC
    jmp QWORD PTR [orig_InternetGetConnectedStateExA]
__proxy_InternetGetConnectedStateExA ENDP

__proxy_InternetGetConnectedStateExW PROC
    jmp QWORD PTR [orig_InternetGetConnectedStateExW]
__proxy_InternetGetConnectedStateExW ENDP

__proxy_InternetGetCookieA PROC
    jmp QWORD PTR [orig_InternetGetCookieA]
__proxy_InternetGetCookieA ENDP

__proxy_InternetGetCookieEx2 PROC
    jmp QWORD PTR [orig_InternetGetCookieEx2]
__proxy_InternetGetCookieEx2 ENDP

__proxy_InternetGetCookieExA PROC
    jmp QWORD PTR [orig_InternetGetCookieExA]
__proxy_InternetGetCookieExA ENDP

__proxy_InternetGetCookieExW PROC
    jmp QWORD PTR [orig_InternetGetCookieExW]
__proxy_InternetGetCookieExW ENDP

__proxy_InternetGetCookieW PROC
    jmp QWORD PTR [orig_InternetGetCookieW]
__proxy_InternetGetCookieW ENDP

__proxy_InternetGetLastResponseInfoA PROC
    jmp QWORD PTR [orig_InternetGetLastResponseInfoA]
__proxy_InternetGetLastResponseInfoA ENDP

__proxy_InternetGetLastResponseInfoW PROC
    jmp QWORD PTR [orig_InternetGetLastResponseInfoW]
__proxy_InternetGetLastResponseInfoW ENDP

__proxy_InternetGetPerSiteCookieDecisionA PROC
    jmp QWORD PTR [orig_InternetGetPerSiteCookieDecisionA]
__proxy_InternetGetPerSiteCookieDecisionA ENDP

__proxy_InternetGetPerSiteCookieDecisionW PROC
    jmp QWORD PTR [orig_InternetGetPerSiteCookieDecisionW]
__proxy_InternetGetPerSiteCookieDecisionW ENDP

__proxy_InternetGetProxyForUrl PROC
    jmp QWORD PTR [orig_InternetGetProxyForUrl]
__proxy_InternetGetProxyForUrl ENDP

__proxy_InternetGetSecurityInfoByURL PROC
    jmp QWORD PTR [orig_InternetGetSecurityInfoByURL]
__proxy_InternetGetSecurityInfoByURL ENDP

__proxy_InternetGetSecurityInfoByURLA PROC
    jmp QWORD PTR [orig_InternetGetSecurityInfoByURLA]
__proxy_InternetGetSecurityInfoByURLA ENDP

__proxy_InternetGetSecurityInfoByURLW PROC
    jmp QWORD PTR [orig_InternetGetSecurityInfoByURLW]
__proxy_InternetGetSecurityInfoByURLW ENDP

__proxy_InternetGoOnline PROC
    jmp QWORD PTR [orig_InternetGoOnline]
__proxy_InternetGoOnline ENDP

__proxy_InternetGoOnlineA PROC
    jmp QWORD PTR [orig_InternetGoOnlineA]
__proxy_InternetGoOnlineA ENDP

__proxy_InternetGoOnlineW PROC
    jmp QWORD PTR [orig_InternetGoOnlineW]
__proxy_InternetGoOnlineW ENDP

__proxy_InternetHangUp PROC
    jmp QWORD PTR [orig_InternetHangUp]
__proxy_InternetHangUp ENDP

__proxy_InternetInitializeAutoProxyDll PROC
    jmp QWORD PTR [orig_InternetInitializeAutoProxyDll]
__proxy_InternetInitializeAutoProxyDll ENDP

__proxy_InternetLockRequestFile PROC
    jmp QWORD PTR [orig_InternetLockRequestFile]
__proxy_InternetLockRequestFile ENDP

__proxy_InternetOpenA PROC
    jmp QWORD PTR [orig_InternetOpenA]
__proxy_InternetOpenA ENDP

__proxy_InternetOpenUrlA PROC
    jmp QWORD PTR [orig_InternetOpenUrlA]
__proxy_InternetOpenUrlA ENDP

__proxy_InternetOpenUrlW PROC
    jmp QWORD PTR [orig_InternetOpenUrlW]
__proxy_InternetOpenUrlW ENDP

__proxy_InternetOpenW PROC
    jmp QWORD PTR [orig_InternetOpenW]
__proxy_InternetOpenW ENDP

__proxy_InternetQueryDataAvailable PROC
    jmp QWORD PTR [orig_InternetQueryDataAvailable]
__proxy_InternetQueryDataAvailable ENDP

__proxy_InternetQueryFortezzaStatus PROC
    jmp QWORD PTR [orig_InternetQueryFortezzaStatus]
__proxy_InternetQueryFortezzaStatus ENDP

__proxy_InternetQueryOptionA PROC
    jmp QWORD PTR [orig_InternetQueryOptionA]
__proxy_InternetQueryOptionA ENDP

__proxy_InternetQueryOptionW PROC
    jmp QWORD PTR [orig_InternetQueryOptionW]
__proxy_InternetQueryOptionW ENDP

__proxy_InternetReadFile PROC
    jmp QWORD PTR [orig_InternetReadFile]
__proxy_InternetReadFile ENDP

__proxy_InternetReadFileExA PROC
    jmp QWORD PTR [orig_InternetReadFileExA]
__proxy_InternetReadFileExA ENDP

__proxy_InternetReadFileExW PROC
    jmp QWORD PTR [orig_InternetReadFileExW]
__proxy_InternetReadFileExW ENDP

__proxy_InternetSecurityProtocolToStringA PROC
    jmp QWORD PTR [orig_InternetSecurityProtocolToStringA]
__proxy_InternetSecurityProtocolToStringA ENDP

__proxy_InternetSecurityProtocolToStringW PROC
    jmp QWORD PTR [orig_InternetSecurityProtocolToStringW]
__proxy_InternetSecurityProtocolToStringW ENDP

__proxy_InternetSetCookieA PROC
    jmp QWORD PTR [orig_InternetSetCookieA]
__proxy_InternetSetCookieA ENDP

__proxy_InternetSetCookieEx2 PROC
    jmp QWORD PTR [orig_InternetSetCookieEx2]
__proxy_InternetSetCookieEx2 ENDP

__proxy_InternetSetCookieExA PROC
    jmp QWORD PTR [orig_InternetSetCookieExA]
__proxy_InternetSetCookieExA ENDP

__proxy_InternetSetCookieExW PROC
    jmp QWORD PTR [orig_InternetSetCookieExW]
__proxy_InternetSetCookieExW ENDP

__proxy_InternetSetCookieW PROC
    jmp QWORD PTR [orig_InternetSetCookieW]
__proxy_InternetSetCookieW ENDP

__proxy_InternetSetDialState PROC
    jmp QWORD PTR [orig_InternetSetDialState]
__proxy_InternetSetDialState ENDP

__proxy_InternetSetDialStateA PROC
    jmp QWORD PTR [orig_InternetSetDialStateA]
__proxy_InternetSetDialStateA ENDP

__proxy_InternetSetDialStateW PROC
    jmp QWORD PTR [orig_InternetSetDialStateW]
__proxy_InternetSetDialStateW ENDP

__proxy_InternetSetFilePointer PROC
    jmp QWORD PTR [orig_InternetSetFilePointer]
__proxy_InternetSetFilePointer ENDP

__proxy_InternetSetOptionA PROC
    jmp QWORD PTR [orig_InternetSetOptionA]
__proxy_InternetSetOptionA ENDP

__proxy_InternetSetOptionExA PROC
    jmp QWORD PTR [orig_InternetSetOptionExA]
__proxy_InternetSetOptionExA ENDP

__proxy_InternetSetOptionExW PROC
    jmp QWORD PTR [orig_InternetSetOptionExW]
__proxy_InternetSetOptionExW ENDP

__proxy_InternetSetOptionW PROC
    jmp QWORD PTR [orig_InternetSetOptionW]
__proxy_InternetSetOptionW ENDP

__proxy_InternetSetPerSiteCookieDecisionA PROC
    jmp QWORD PTR [orig_InternetSetPerSiteCookieDecisionA]
__proxy_InternetSetPerSiteCookieDecisionA ENDP

__proxy_InternetSetPerSiteCookieDecisionW PROC
    jmp QWORD PTR [orig_InternetSetPerSiteCookieDecisionW]
__proxy_InternetSetPerSiteCookieDecisionW ENDP

__proxy_InternetSetSecureLegacyServersAppCompat PROC
    jmp QWORD PTR [orig_InternetSetSecureLegacyServersAppCompat]
__proxy_InternetSetSecureLegacyServersAppCompat ENDP

__proxy_InternetSetStatusCallback PROC
    jmp QWORD PTR [orig_InternetSetStatusCallback]
__proxy_InternetSetStatusCallback ENDP

__proxy_InternetSetStatusCallbackA PROC
    jmp QWORD PTR [orig_InternetSetStatusCallbackA]
__proxy_InternetSetStatusCallbackA ENDP

__proxy_InternetSetStatusCallbackW PROC
    jmp QWORD PTR [orig_InternetSetStatusCallbackW]
__proxy_InternetSetStatusCallbackW ENDP

__proxy_InternetShowSecurityInfoByURL PROC
    jmp QWORD PTR [orig_InternetShowSecurityInfoByURL]
__proxy_InternetShowSecurityInfoByURL ENDP

__proxy_InternetShowSecurityInfoByURLA PROC
    jmp QWORD PTR [orig_InternetShowSecurityInfoByURLA]
__proxy_InternetShowSecurityInfoByURLA ENDP

__proxy_InternetShowSecurityInfoByURLW PROC
    jmp QWORD PTR [orig_InternetShowSecurityInfoByURLW]
__proxy_InternetShowSecurityInfoByURLW ENDP

__proxy_InternetTimeFromSystemTime PROC
    jmp QWORD PTR [orig_InternetTimeFromSystemTime]
__proxy_InternetTimeFromSystemTime ENDP

__proxy_InternetTimeFromSystemTimeA PROC
    jmp QWORD PTR [orig_InternetTimeFromSystemTimeA]
__proxy_InternetTimeFromSystemTimeA ENDP

__proxy_InternetTimeFromSystemTimeW PROC
    jmp QWORD PTR [orig_InternetTimeFromSystemTimeW]
__proxy_InternetTimeFromSystemTimeW ENDP

__proxy_InternetTimeToSystemTime PROC
    jmp QWORD PTR [orig_InternetTimeToSystemTime]
__proxy_InternetTimeToSystemTime ENDP

__proxy_InternetTimeToSystemTimeA PROC
    jmp QWORD PTR [orig_InternetTimeToSystemTimeA]
__proxy_InternetTimeToSystemTimeA ENDP

__proxy_InternetTimeToSystemTimeW PROC
    jmp QWORD PTR [orig_InternetTimeToSystemTimeW]
__proxy_InternetTimeToSystemTimeW ENDP

__proxy_InternetUnlockRequestFile PROC
    jmp QWORD PTR [orig_InternetUnlockRequestFile]
__proxy_InternetUnlockRequestFile ENDP

__proxy_InternetWriteFile PROC
    jmp QWORD PTR [orig_InternetWriteFile]
__proxy_InternetWriteFile ENDP

__proxy_InternetWriteFileExA PROC
    jmp QWORD PTR [orig_InternetWriteFileExA]
__proxy_InternetWriteFileExA ENDP

__proxy_InternetWriteFileExW PROC
    jmp QWORD PTR [orig_InternetWriteFileExW]
__proxy_InternetWriteFileExW ENDP

__proxy_IsHostInProxyBypassList PROC
    jmp QWORD PTR [orig_IsHostInProxyBypassList]
__proxy_IsHostInProxyBypassList ENDP

__proxy_IsUrlCacheEntryExpiredA PROC
    jmp QWORD PTR [orig_IsUrlCacheEntryExpiredA]
__proxy_IsUrlCacheEntryExpiredA ENDP

__proxy_IsUrlCacheEntryExpiredW PROC
    jmp QWORD PTR [orig_IsUrlCacheEntryExpiredW]
__proxy_IsUrlCacheEntryExpiredW ENDP

__proxy_LoadUrlCacheContent PROC
    jmp QWORD PTR [orig_LoadUrlCacheContent]
__proxy_LoadUrlCacheContent ENDP

__proxy_ParseX509EncodedCertificateForListBoxEntry PROC
    jmp QWORD PTR [orig_ParseX509EncodedCertificateForListBoxEntry]
__proxy_ParseX509EncodedCertificateForListBoxEntry ENDP

__proxy_PrivacyGetZonePreferenceW PROC
    jmp QWORD PTR [orig_PrivacyGetZonePreferenceW]
__proxy_PrivacyGetZonePreferenceW ENDP

__proxy_PrivacySetZonePreferenceW PROC
    jmp QWORD PTR [orig_PrivacySetZonePreferenceW]
__proxy_PrivacySetZonePreferenceW ENDP

__proxy_ReadUrlCacheEntryStream PROC
    jmp QWORD PTR [orig_ReadUrlCacheEntryStream]
__proxy_ReadUrlCacheEntryStream ENDP

__proxy_ReadUrlCacheEntryStreamEx PROC
    jmp QWORD PTR [orig_ReadUrlCacheEntryStreamEx]
__proxy_ReadUrlCacheEntryStreamEx ENDP

__proxy_RegisterUrlCacheNotification PROC
    jmp QWORD PTR [orig_RegisterUrlCacheNotification]
__proxy_RegisterUrlCacheNotification ENDP

__proxy_ResumeSuspendedDownload PROC
    jmp QWORD PTR [orig_ResumeSuspendedDownload]
__proxy_ResumeSuspendedDownload ENDP

__proxy_RetrieveUrlCacheEntryFileA PROC
    jmp QWORD PTR [orig_RetrieveUrlCacheEntryFileA]
__proxy_RetrieveUrlCacheEntryFileA ENDP

__proxy_RetrieveUrlCacheEntryFileW PROC
    jmp QWORD PTR [orig_RetrieveUrlCacheEntryFileW]
__proxy_RetrieveUrlCacheEntryFileW ENDP

__proxy_RetrieveUrlCacheEntryStreamA PROC
    jmp QWORD PTR [orig_RetrieveUrlCacheEntryStreamA]
__proxy_RetrieveUrlCacheEntryStreamA ENDP

__proxy_RetrieveUrlCacheEntryStreamW PROC
    jmp QWORD PTR [orig_RetrieveUrlCacheEntryStreamW]
__proxy_RetrieveUrlCacheEntryStreamW ENDP

__proxy_RunOnceUrlCache PROC
    jmp QWORD PTR [orig_RunOnceUrlCache]
__proxy_RunOnceUrlCache ENDP

__proxy_SetUrlCacheConfigInfoA PROC
    jmp QWORD PTR [orig_SetUrlCacheConfigInfoA]
__proxy_SetUrlCacheConfigInfoA ENDP

__proxy_SetUrlCacheConfigInfoW PROC
    jmp QWORD PTR [orig_SetUrlCacheConfigInfoW]
__proxy_SetUrlCacheConfigInfoW ENDP

__proxy_SetUrlCacheEntryGroup PROC
    jmp QWORD PTR [orig_SetUrlCacheEntryGroup]
__proxy_SetUrlCacheEntryGroup ENDP

__proxy_SetUrlCacheEntryGroupA PROC
    jmp QWORD PTR [orig_SetUrlCacheEntryGroupA]
__proxy_SetUrlCacheEntryGroupA ENDP

__proxy_SetUrlCacheEntryGroupW PROC
    jmp QWORD PTR [orig_SetUrlCacheEntryGroupW]
__proxy_SetUrlCacheEntryGroupW ENDP

__proxy_SetUrlCacheEntryInfoA PROC
    jmp QWORD PTR [orig_SetUrlCacheEntryInfoA]
__proxy_SetUrlCacheEntryInfoA ENDP

__proxy_SetUrlCacheEntryInfoW PROC
    jmp QWORD PTR [orig_SetUrlCacheEntryInfoW]
__proxy_SetUrlCacheEntryInfoW ENDP

__proxy_SetUrlCacheGroupAttributeA PROC
    jmp QWORD PTR [orig_SetUrlCacheGroupAttributeA]
__proxy_SetUrlCacheGroupAttributeA ENDP

__proxy_SetUrlCacheGroupAttributeW PROC
    jmp QWORD PTR [orig_SetUrlCacheGroupAttributeW]
__proxy_SetUrlCacheGroupAttributeW ENDP

__proxy_SetUrlCacheHeaderData PROC
    jmp QWORD PTR [orig_SetUrlCacheHeaderData]
__proxy_SetUrlCacheHeaderData ENDP

__proxy_ShowCertificate PROC
    jmp QWORD PTR [orig_ShowCertificate]
__proxy_ShowCertificate ENDP

__proxy_ShowClientAuthCerts PROC
    jmp QWORD PTR [orig_ShowClientAuthCerts]
__proxy_ShowClientAuthCerts ENDP

__proxy_ShowSecurityInfo PROC
    jmp QWORD PTR [orig_ShowSecurityInfo]
__proxy_ShowSecurityInfo ENDP

__proxy_ShowX509EncodedCertificate PROC
    jmp QWORD PTR [orig_ShowX509EncodedCertificate]
__proxy_ShowX509EncodedCertificate ENDP

__proxy_UnlockUrlCacheEntryFile PROC
    jmp QWORD PTR [orig_UnlockUrlCacheEntryFile]
__proxy_UnlockUrlCacheEntryFile ENDP

__proxy_UnlockUrlCacheEntryFileA PROC
    jmp QWORD PTR [orig_UnlockUrlCacheEntryFileA]
__proxy_UnlockUrlCacheEntryFileA ENDP

__proxy_UnlockUrlCacheEntryFileW PROC
    jmp QWORD PTR [orig_UnlockUrlCacheEntryFileW]
__proxy_UnlockUrlCacheEntryFileW ENDP

__proxy_UnlockUrlCacheEntryStream PROC
    jmp QWORD PTR [orig_UnlockUrlCacheEntryStream]
__proxy_UnlockUrlCacheEntryStream ENDP

__proxy_UpdateUrlCacheContentPath PROC
    jmp QWORD PTR [orig_UpdateUrlCacheContentPath]
__proxy_UpdateUrlCacheContentPath ENDP

__proxy_UrlCacheCheckEntriesExist PROC
    jmp QWORD PTR [orig_UrlCacheCheckEntriesExist]
__proxy_UrlCacheCheckEntriesExist ENDP

__proxy_UrlCacheCloseEntryHandle PROC
    jmp QWORD PTR [orig_UrlCacheCloseEntryHandle]
__proxy_UrlCacheCloseEntryHandle ENDP

__proxy_UrlCacheContainerSetEntryMaximumAge PROC
    jmp QWORD PTR [orig_UrlCacheContainerSetEntryMaximumAge]
__proxy_UrlCacheContainerSetEntryMaximumAge ENDP

__proxy_UrlCacheCreateContainer PROC
    jmp QWORD PTR [orig_UrlCacheCreateContainer]
__proxy_UrlCacheCreateContainer ENDP

__proxy_UrlCacheFindFirstEntry PROC
    jmp QWORD PTR [orig_UrlCacheFindFirstEntry]
__proxy_UrlCacheFindFirstEntry ENDP

__proxy_UrlCacheFindNextEntry PROC
    jmp QWORD PTR [orig_UrlCacheFindNextEntry]
__proxy_UrlCacheFindNextEntry ENDP

__proxy_UrlCacheFreeEntryInfo PROC
    jmp QWORD PTR [orig_UrlCacheFreeEntryInfo]
__proxy_UrlCacheFreeEntryInfo ENDP

__proxy_UrlCacheFreeGlobalSpace PROC
    jmp QWORD PTR [orig_UrlCacheFreeGlobalSpace]
__proxy_UrlCacheFreeGlobalSpace ENDP

__proxy_UrlCacheGetContentPaths PROC
    jmp QWORD PTR [orig_UrlCacheGetContentPaths]
__proxy_UrlCacheGetContentPaths ENDP

__proxy_UrlCacheGetEntryInfo PROC
    jmp QWORD PTR [orig_UrlCacheGetEntryInfo]
__proxy_UrlCacheGetEntryInfo ENDP

__proxy_UrlCacheGetGlobalCacheSize PROC
    jmp QWORD PTR [orig_UrlCacheGetGlobalCacheSize]
__proxy_UrlCacheGetGlobalCacheSize ENDP

__proxy_UrlCacheGetGlobalLimit PROC
    jmp QWORD PTR [orig_UrlCacheGetGlobalLimit]
__proxy_UrlCacheGetGlobalLimit ENDP

__proxy_UrlCacheReadEntryStream PROC
    jmp QWORD PTR [orig_UrlCacheReadEntryStream]
__proxy_UrlCacheReadEntryStream ENDP

__proxy_UrlCacheReloadSettings PROC
    jmp QWORD PTR [orig_UrlCacheReloadSettings]
__proxy_UrlCacheReloadSettings ENDP

__proxy_UrlCacheRetrieveEntryFile PROC
    jmp QWORD PTR [orig_UrlCacheRetrieveEntryFile]
__proxy_UrlCacheRetrieveEntryFile ENDP

__proxy_UrlCacheRetrieveEntryStream PROC
    jmp QWORD PTR [orig_UrlCacheRetrieveEntryStream]
__proxy_UrlCacheRetrieveEntryStream ENDP

__proxy_UrlCacheServer PROC
    jmp QWORD PTR [orig_UrlCacheServer]
__proxy_UrlCacheServer ENDP

__proxy_UrlCacheSetGlobalLimit PROC
    jmp QWORD PTR [orig_UrlCacheSetGlobalLimit]
__proxy_UrlCacheSetGlobalLimit ENDP

__proxy_UrlCacheUpdateEntryExtraData PROC
    jmp QWORD PTR [orig_UrlCacheUpdateEntryExtraData]
__proxy_UrlCacheUpdateEntryExtraData ENDP

__proxy_UrlZonesDetach PROC
    jmp QWORD PTR [orig_UrlZonesDetach]
__proxy_UrlZonesDetach ENDP

__proxy__GetFileExtensionFromUrl PROC
    jmp QWORD PTR [orig__GetFileExtensionFromUrl]
__proxy__GetFileExtensionFromUrl ENDP

__proxy_DllCanUnloadNow PROC
    jmp QWORD PTR [orig_DllCanUnloadNow]
__proxy_DllCanUnloadNow ENDP

__proxy_DllGetClassObject PROC
    jmp QWORD PTR [orig_DllGetClassObject]
__proxy_DllGetClassObject ENDP

__proxy_DllInstall PROC
    jmp QWORD PTR [orig_DllInstall]
__proxy_DllInstall ENDP

__proxy_DllRegisterServer PROC
    jmp QWORD PTR [orig_DllRegisterServer]
__proxy_DllRegisterServer ENDP

__proxy_DllUnregisterServer PROC
    jmp QWORD PTR [orig_DllUnregisterServer]
__proxy_DllUnregisterServer ENDP

__proxy_ord101 PROC
    jmp QWORD PTR [orig___proxy_ord101]
__proxy_ord101 ENDP

__proxy_ord102 PROC
    jmp QWORD PTR [orig___proxy_ord102]
__proxy_ord102 ENDP

__proxy_ord103 PROC
    jmp QWORD PTR [orig___proxy_ord103]
__proxy_ord103 ENDP

__proxy_ord104 PROC
    jmp QWORD PTR [orig___proxy_ord104]
__proxy_ord104 ENDP

__proxy_ord105 PROC
    jmp QWORD PTR [orig___proxy_ord105]
__proxy_ord105 ENDP

__proxy_ord108 PROC
    jmp QWORD PTR [orig___proxy_ord108]
__proxy_ord108 ENDP

__proxy_ord109 PROC
    jmp QWORD PTR [orig___proxy_ord109]
__proxy_ord109 ENDP

__proxy_ord110 PROC
    jmp QWORD PTR [orig___proxy_ord110]
__proxy_ord110 ENDP

__proxy_ord111 PROC
    jmp QWORD PTR [orig___proxy_ord111]
__proxy_ord111 ENDP

__proxy_ord112 PROC
    jmp QWORD PTR [orig___proxy_ord112]
__proxy_ord112 ENDP

__proxy_ord116 PROC
    jmp QWORD PTR [orig___proxy_ord116]
__proxy_ord116 ENDP

__proxy_ord117 PROC
    jmp QWORD PTR [orig___proxy_ord117]
__proxy_ord117 ENDP

__proxy_ord118 PROC
    jmp QWORD PTR [orig___proxy_ord118]
__proxy_ord118 ENDP

__proxy_ord120 PROC
    jmp QWORD PTR [orig___proxy_ord120]
__proxy_ord120 ENDP

__proxy_ord121 PROC
    jmp QWORD PTR [orig___proxy_ord121]
__proxy_ord121 ENDP

__proxy_ord122 PROC
    jmp QWORD PTR [orig___proxy_ord122]
__proxy_ord122 ENDP

__proxy_ord123 PROC
    jmp QWORD PTR [orig___proxy_ord123]
__proxy_ord123 ENDP

__proxy_ord346 PROC
    jmp QWORD PTR [orig___proxy_ord346]
__proxy_ord346 ENDP

__proxy_ord401 PROC
    jmp QWORD PTR [orig___proxy_ord401]
__proxy_ord401 ENDP

__proxy_ord402 PROC
    jmp QWORD PTR [orig___proxy_ord402]
__proxy_ord402 ENDP

__proxy_ord403 PROC
    jmp QWORD PTR [orig___proxy_ord403]
__proxy_ord403 ENDP

__proxy_ord410 PROC
    jmp QWORD PTR [orig___proxy_ord410]
__proxy_ord410 ENDP

__proxy_ord411 PROC
    jmp QWORD PTR [orig___proxy_ord411]
__proxy_ord411 ENDP

__proxy_ord413 PROC
    jmp QWORD PTR [orig___proxy_ord413]
__proxy_ord413 ENDP

__proxy_ord420 PROC
    jmp QWORD PTR [orig___proxy_ord420]
__proxy_ord420 ENDP

__proxy_ord421 PROC
    jmp QWORD PTR [orig___proxy_ord421]
__proxy_ord421 ENDP

__proxy_ord422 PROC
    jmp QWORD PTR [orig___proxy_ord422]
__proxy_ord422 ENDP

__proxy_ord423 PROC
    jmp QWORD PTR [orig___proxy_ord423]
__proxy_ord423 ENDP

END
