; Auto-generated RUNTIME forwarding thunks for winmm.dll
; Generated by extract_exports.py (runtime mode)
;
; Each function is a simple JMP through a function pointer.
; The function pointers (orig_*) are defined in winmm_runtime.h
; and initialized by LoadOriginalDLL() at runtime.
;
; Total thunks: 181
; Architecture: x64 only
; Assembler: MASM (ml64.exe)

.data
EXTERNDEF orig_mciExecute : QWORD
EXTERNDEF orig_CloseDriver : QWORD
EXTERNDEF orig_DefDriverProc : QWORD
EXTERNDEF orig_DriverCallback : QWORD
EXTERNDEF orig_DrvGetModuleHandle : QWORD
EXTERNDEF orig_GetDriverModuleHandle : QWORD
EXTERNDEF orig_OpenDriver : QWORD
EXTERNDEF orig_PlaySound : QWORD
EXTERNDEF orig_PlaySoundA : QWORD
EXTERNDEF orig_PlaySoundW : QWORD
EXTERNDEF orig_SendDriverMessage : QWORD
EXTERNDEF orig_WOWAppExit : QWORD
EXTERNDEF orig_auxGetDevCapsA : QWORD
EXTERNDEF orig_auxGetDevCapsW : QWORD
EXTERNDEF orig_auxGetNumDevs : QWORD
EXTERNDEF orig_auxGetVolume : QWORD
EXTERNDEF orig_auxOutMessage : QWORD
EXTERNDEF orig_auxSetVolume : QWORD
EXTERNDEF orig_joyConfigChanged : QWORD
EXTERNDEF orig_joyGetDevCapsA : QWORD
EXTERNDEF orig_joyGetDevCapsW : QWORD
EXTERNDEF orig_joyGetNumDevs : QWORD
EXTERNDEF orig_joyGetPos : QWORD
EXTERNDEF orig_joyGetPosEx : QWORD
EXTERNDEF orig_joyGetThreshold : QWORD
EXTERNDEF orig_joyReleaseCapture : QWORD
EXTERNDEF orig_joySetCapture : QWORD
EXTERNDEF orig_joySetThreshold : QWORD
EXTERNDEF orig_mciDriverNotify : QWORD
EXTERNDEF orig_mciDriverYield : QWORD
EXTERNDEF orig_mciFreeCommandResource : QWORD
EXTERNDEF orig_mciGetCreatorTask : QWORD
EXTERNDEF orig_mciGetDeviceIDA : QWORD
EXTERNDEF orig_mciGetDeviceIDFromElementIDA : QWORD
EXTERNDEF orig_mciGetDeviceIDFromElementIDW : QWORD
EXTERNDEF orig_mciGetDeviceIDW : QWORD
EXTERNDEF orig_mciGetDriverData : QWORD
EXTERNDEF orig_mciGetErrorStringA : QWORD
EXTERNDEF orig_mciGetErrorStringW : QWORD
EXTERNDEF orig_mciGetYieldProc : QWORD
EXTERNDEF orig_mciLoadCommandResource : QWORD
EXTERNDEF orig_mciSendCommandA : QWORD
EXTERNDEF orig_mciSendCommandW : QWORD
EXTERNDEF orig_mciSendStringA : QWORD
EXTERNDEF orig_mciSendStringW : QWORD
EXTERNDEF orig_mciSetDriverData : QWORD
EXTERNDEF orig_mciSetYieldProc : QWORD
EXTERNDEF orig_midiConnect : QWORD
EXTERNDEF orig_midiDisconnect : QWORD
EXTERNDEF orig_midiInAddBuffer : QWORD
EXTERNDEF orig_midiInClose : QWORD
EXTERNDEF orig_midiInGetDevCapsA : QWORD
EXTERNDEF orig_midiInGetDevCapsW : QWORD
EXTERNDEF orig_midiInGetErrorTextA : QWORD
EXTERNDEF orig_midiInGetErrorTextW : QWORD
EXTERNDEF orig_midiInGetID : QWORD
EXTERNDEF orig_midiInGetNumDevs : QWORD
EXTERNDEF orig_midiInMessage : QWORD
EXTERNDEF orig_midiInOpen : QWORD
EXTERNDEF orig_midiInPrepareHeader : QWORD
EXTERNDEF orig_midiInReset : QWORD
EXTERNDEF orig_midiInStart : QWORD
EXTERNDEF orig_midiInStop : QWORD
EXTERNDEF orig_midiInUnprepareHeader : QWORD
EXTERNDEF orig_midiOutCacheDrumPatches : QWORD
EXTERNDEF orig_midiOutCachePatches : QWORD
EXTERNDEF orig_midiOutClose : QWORD
EXTERNDEF orig_midiOutGetDevCapsA : QWORD
EXTERNDEF orig_midiOutGetDevCapsW : QWORD
EXTERNDEF orig_midiOutGetErrorTextA : QWORD
EXTERNDEF orig_midiOutGetErrorTextW : QWORD
EXTERNDEF orig_midiOutGetID : QWORD
EXTERNDEF orig_midiOutGetNumDevs : QWORD
EXTERNDEF orig_midiOutGetVolume : QWORD
EXTERNDEF orig_midiOutLongMsg : QWORD
EXTERNDEF orig_midiOutMessage : QWORD
EXTERNDEF orig_midiOutOpen : QWORD
EXTERNDEF orig_midiOutPrepareHeader : QWORD
EXTERNDEF orig_midiOutReset : QWORD
EXTERNDEF orig_midiOutSetVolume : QWORD
EXTERNDEF orig_midiOutShortMsg : QWORD
EXTERNDEF orig_midiOutUnprepareHeader : QWORD
EXTERNDEF orig_midiStreamClose : QWORD
EXTERNDEF orig_midiStreamOpen : QWORD
EXTERNDEF orig_midiStreamOut : QWORD
EXTERNDEF orig_midiStreamPause : QWORD
EXTERNDEF orig_midiStreamPosition : QWORD
EXTERNDEF orig_midiStreamProperty : QWORD
EXTERNDEF orig_midiStreamRestart : QWORD
EXTERNDEF orig_midiStreamStop : QWORD
EXTERNDEF orig_mixerClose : QWORD
EXTERNDEF orig_mixerGetControlDetailsA : QWORD
EXTERNDEF orig_mixerGetControlDetailsW : QWORD
EXTERNDEF orig_mixerGetDevCapsA : QWORD
EXTERNDEF orig_mixerGetDevCapsW : QWORD
EXTERNDEF orig_mixerGetID : QWORD
EXTERNDEF orig_mixerGetLineControlsA : QWORD
EXTERNDEF orig_mixerGetLineControlsW : QWORD
EXTERNDEF orig_mixerGetLineInfoA : QWORD
EXTERNDEF orig_mixerGetLineInfoW : QWORD
EXTERNDEF orig_mixerGetNumDevs : QWORD
EXTERNDEF orig_mixerMessage : QWORD
EXTERNDEF orig_mixerOpen : QWORD
EXTERNDEF orig_mixerSetControlDetails : QWORD
EXTERNDEF orig_mmDrvInstall : QWORD
EXTERNDEF orig_mmGetCurrentTask : QWORD
EXTERNDEF orig_mmTaskBlock : QWORD
EXTERNDEF orig_mmTaskCreate : QWORD
EXTERNDEF orig_mmTaskSignal : QWORD
EXTERNDEF orig_mmTaskYield : QWORD
EXTERNDEF orig_mmioAdvance : QWORD
EXTERNDEF orig_mmioAscend : QWORD
EXTERNDEF orig_mmioClose : QWORD
EXTERNDEF orig_mmioCreateChunk : QWORD
EXTERNDEF orig_mmioDescend : QWORD
EXTERNDEF orig_mmioFlush : QWORD
EXTERNDEF orig_mmioGetInfo : QWORD
EXTERNDEF orig_mmioInstallIOProcA : QWORD
EXTERNDEF orig_mmioInstallIOProcW : QWORD
EXTERNDEF orig_mmioOpenA : QWORD
EXTERNDEF orig_mmioOpenW : QWORD
EXTERNDEF orig_mmioRead : QWORD
EXTERNDEF orig_mmioRenameA : QWORD
EXTERNDEF orig_mmioRenameW : QWORD
EXTERNDEF orig_mmioSeek : QWORD
EXTERNDEF orig_mmioSendMessage : QWORD
EXTERNDEF orig_mmioSetBuffer : QWORD
EXTERNDEF orig_mmioSetInfo : QWORD
EXTERNDEF orig_mmioStringToFOURCCA : QWORD
EXTERNDEF orig_mmioStringToFOURCCW : QWORD
EXTERNDEF orig_mmioWrite : QWORD
EXTERNDEF orig_mmsystemGetVersion : QWORD
EXTERNDEF orig_sndPlaySoundA : QWORD
EXTERNDEF orig_sndPlaySoundW : QWORD
EXTERNDEF orig_timeBeginPeriod : QWORD
EXTERNDEF orig_timeEndPeriod : QWORD
EXTERNDEF orig_timeGetDevCaps : QWORD
EXTERNDEF orig_timeGetSystemTime : QWORD
EXTERNDEF orig_timeGetTime : QWORD
EXTERNDEF orig_timeKillEvent : QWORD
EXTERNDEF orig_timeSetEvent : QWORD
EXTERNDEF orig_waveInAddBuffer : QWORD
EXTERNDEF orig_waveInClose : QWORD
EXTERNDEF orig_waveInGetDevCapsA : QWORD
EXTERNDEF orig_waveInGetDevCapsW : QWORD
EXTERNDEF orig_waveInGetErrorTextA : QWORD
EXTERNDEF orig_waveInGetErrorTextW : QWORD
EXTERNDEF orig_waveInGetID : QWORD
EXTERNDEF orig_waveInGetNumDevs : QWORD
EXTERNDEF orig_waveInGetPosition : QWORD
EXTERNDEF orig_waveInMessage : QWORD
EXTERNDEF orig_waveInOpen : QWORD
EXTERNDEF orig_waveInPrepareHeader : QWORD
EXTERNDEF orig_waveInReset : QWORD
EXTERNDEF orig_waveInStart : QWORD
EXTERNDEF orig_waveInStop : QWORD
EXTERNDEF orig_waveInUnprepareHeader : QWORD
EXTERNDEF orig_waveOutBreakLoop : QWORD
EXTERNDEF orig_waveOutClose : QWORD
EXTERNDEF orig_waveOutGetDevCapsA : QWORD
EXTERNDEF orig_waveOutGetDevCapsW : QWORD
EXTERNDEF orig_waveOutGetErrorTextA : QWORD
EXTERNDEF orig_waveOutGetErrorTextW : QWORD
EXTERNDEF orig_waveOutGetID : QWORD
EXTERNDEF orig_waveOutGetNumDevs : QWORD
EXTERNDEF orig_waveOutGetPitch : QWORD
EXTERNDEF orig_waveOutGetPlaybackRate : QWORD
EXTERNDEF orig_waveOutGetPosition : QWORD
EXTERNDEF orig_waveOutGetVolume : QWORD
EXTERNDEF orig_waveOutMessage : QWORD
EXTERNDEF orig_waveOutOpen : QWORD
EXTERNDEF orig_waveOutPause : QWORD
EXTERNDEF orig_waveOutPrepareHeader : QWORD
EXTERNDEF orig_waveOutReset : QWORD
EXTERNDEF orig_waveOutRestart : QWORD
EXTERNDEF orig_waveOutSetPitch : QWORD
EXTERNDEF orig_waveOutSetPlaybackRate : QWORD
EXTERNDEF orig_waveOutSetVolume : QWORD
EXTERNDEF orig_waveOutUnprepareHeader : QWORD
EXTERNDEF orig_waveOutWrite : QWORD
EXTERNDEF orig___proxy_ord2 : QWORD

.code

__proxy_mciExecute PROC
    jmp QWORD PTR [orig_mciExecute]
__proxy_mciExecute ENDP

__proxy_CloseDriver PROC
    jmp QWORD PTR [orig_CloseDriver]
__proxy_CloseDriver ENDP

__proxy_DefDriverProc PROC
    jmp QWORD PTR [orig_DefDriverProc]
__proxy_DefDriverProc ENDP

__proxy_DriverCallback PROC
    jmp QWORD PTR [orig_DriverCallback]
__proxy_DriverCallback ENDP

__proxy_DrvGetModuleHandle PROC
    jmp QWORD PTR [orig_DrvGetModuleHandle]
__proxy_DrvGetModuleHandle ENDP

__proxy_GetDriverModuleHandle PROC
    jmp QWORD PTR [orig_GetDriverModuleHandle]
__proxy_GetDriverModuleHandle ENDP

__proxy_OpenDriver PROC
    jmp QWORD PTR [orig_OpenDriver]
__proxy_OpenDriver ENDP

__proxy_PlaySound PROC
    jmp QWORD PTR [orig_PlaySound]
__proxy_PlaySound ENDP

__proxy_PlaySoundA PROC
    jmp QWORD PTR [orig_PlaySoundA]
__proxy_PlaySoundA ENDP

__proxy_PlaySoundW PROC
    jmp QWORD PTR [orig_PlaySoundW]
__proxy_PlaySoundW ENDP

__proxy_SendDriverMessage PROC
    jmp QWORD PTR [orig_SendDriverMessage]
__proxy_SendDriverMessage ENDP

__proxy_WOWAppExit PROC
    jmp QWORD PTR [orig_WOWAppExit]
__proxy_WOWAppExit ENDP

__proxy_auxGetDevCapsA PROC
    jmp QWORD PTR [orig_auxGetDevCapsA]
__proxy_auxGetDevCapsA ENDP

__proxy_auxGetDevCapsW PROC
    jmp QWORD PTR [orig_auxGetDevCapsW]
__proxy_auxGetDevCapsW ENDP

__proxy_auxGetNumDevs PROC
    jmp QWORD PTR [orig_auxGetNumDevs]
__proxy_auxGetNumDevs ENDP

__proxy_auxGetVolume PROC
    jmp QWORD PTR [orig_auxGetVolume]
__proxy_auxGetVolume ENDP

__proxy_auxOutMessage PROC
    jmp QWORD PTR [orig_auxOutMessage]
__proxy_auxOutMessage ENDP

__proxy_auxSetVolume PROC
    jmp QWORD PTR [orig_auxSetVolume]
__proxy_auxSetVolume ENDP

__proxy_joyConfigChanged PROC
    jmp QWORD PTR [orig_joyConfigChanged]
__proxy_joyConfigChanged ENDP

__proxy_joyGetDevCapsA PROC
    jmp QWORD PTR [orig_joyGetDevCapsA]
__proxy_joyGetDevCapsA ENDP

__proxy_joyGetDevCapsW PROC
    jmp QWORD PTR [orig_joyGetDevCapsW]
__proxy_joyGetDevCapsW ENDP

__proxy_joyGetNumDevs PROC
    jmp QWORD PTR [orig_joyGetNumDevs]
__proxy_joyGetNumDevs ENDP

__proxy_joyGetPos PROC
    jmp QWORD PTR [orig_joyGetPos]
__proxy_joyGetPos ENDP

__proxy_joyGetPosEx PROC
    jmp QWORD PTR [orig_joyGetPosEx]
__proxy_joyGetPosEx ENDP

__proxy_joyGetThreshold PROC
    jmp QWORD PTR [orig_joyGetThreshold]
__proxy_joyGetThreshold ENDP

__proxy_joyReleaseCapture PROC
    jmp QWORD PTR [orig_joyReleaseCapture]
__proxy_joyReleaseCapture ENDP

__proxy_joySetCapture PROC
    jmp QWORD PTR [orig_joySetCapture]
__proxy_joySetCapture ENDP

__proxy_joySetThreshold PROC
    jmp QWORD PTR [orig_joySetThreshold]
__proxy_joySetThreshold ENDP

__proxy_mciDriverNotify PROC
    jmp QWORD PTR [orig_mciDriverNotify]
__proxy_mciDriverNotify ENDP

__proxy_mciDriverYield PROC
    jmp QWORD PTR [orig_mciDriverYield]
__proxy_mciDriverYield ENDP

__proxy_mciFreeCommandResource PROC
    jmp QWORD PTR [orig_mciFreeCommandResource]
__proxy_mciFreeCommandResource ENDP

__proxy_mciGetCreatorTask PROC
    jmp QWORD PTR [orig_mciGetCreatorTask]
__proxy_mciGetCreatorTask ENDP

__proxy_mciGetDeviceIDA PROC
    jmp QWORD PTR [orig_mciGetDeviceIDA]
__proxy_mciGetDeviceIDA ENDP

__proxy_mciGetDeviceIDFromElementIDA PROC
    jmp QWORD PTR [orig_mciGetDeviceIDFromElementIDA]
__proxy_mciGetDeviceIDFromElementIDA ENDP

__proxy_mciGetDeviceIDFromElementIDW PROC
    jmp QWORD PTR [orig_mciGetDeviceIDFromElementIDW]
__proxy_mciGetDeviceIDFromElementIDW ENDP

__proxy_mciGetDeviceIDW PROC
    jmp QWORD PTR [orig_mciGetDeviceIDW]
__proxy_mciGetDeviceIDW ENDP

__proxy_mciGetDriverData PROC
    jmp QWORD PTR [orig_mciGetDriverData]
__proxy_mciGetDriverData ENDP

__proxy_mciGetErrorStringA PROC
    jmp QWORD PTR [orig_mciGetErrorStringA]
__proxy_mciGetErrorStringA ENDP

__proxy_mciGetErrorStringW PROC
    jmp QWORD PTR [orig_mciGetErrorStringW]
__proxy_mciGetErrorStringW ENDP

__proxy_mciGetYieldProc PROC
    jmp QWORD PTR [orig_mciGetYieldProc]
__proxy_mciGetYieldProc ENDP

__proxy_mciLoadCommandResource PROC
    jmp QWORD PTR [orig_mciLoadCommandResource]
__proxy_mciLoadCommandResource ENDP

__proxy_mciSendCommandA PROC
    jmp QWORD PTR [orig_mciSendCommandA]
__proxy_mciSendCommandA ENDP

__proxy_mciSendCommandW PROC
    jmp QWORD PTR [orig_mciSendCommandW]
__proxy_mciSendCommandW ENDP

__proxy_mciSendStringA PROC
    jmp QWORD PTR [orig_mciSendStringA]
__proxy_mciSendStringA ENDP

__proxy_mciSendStringW PROC
    jmp QWORD PTR [orig_mciSendStringW]
__proxy_mciSendStringW ENDP

__proxy_mciSetDriverData PROC
    jmp QWORD PTR [orig_mciSetDriverData]
__proxy_mciSetDriverData ENDP

__proxy_mciSetYieldProc PROC
    jmp QWORD PTR [orig_mciSetYieldProc]
__proxy_mciSetYieldProc ENDP

__proxy_midiConnect PROC
    jmp QWORD PTR [orig_midiConnect]
__proxy_midiConnect ENDP

__proxy_midiDisconnect PROC
    jmp QWORD PTR [orig_midiDisconnect]
__proxy_midiDisconnect ENDP

__proxy_midiInAddBuffer PROC
    jmp QWORD PTR [orig_midiInAddBuffer]
__proxy_midiInAddBuffer ENDP

__proxy_midiInClose PROC
    jmp QWORD PTR [orig_midiInClose]
__proxy_midiInClose ENDP

__proxy_midiInGetDevCapsA PROC
    jmp QWORD PTR [orig_midiInGetDevCapsA]
__proxy_midiInGetDevCapsA ENDP

__proxy_midiInGetDevCapsW PROC
    jmp QWORD PTR [orig_midiInGetDevCapsW]
__proxy_midiInGetDevCapsW ENDP

__proxy_midiInGetErrorTextA PROC
    jmp QWORD PTR [orig_midiInGetErrorTextA]
__proxy_midiInGetErrorTextA ENDP

__proxy_midiInGetErrorTextW PROC
    jmp QWORD PTR [orig_midiInGetErrorTextW]
__proxy_midiInGetErrorTextW ENDP

__proxy_midiInGetID PROC
    jmp QWORD PTR [orig_midiInGetID]
__proxy_midiInGetID ENDP

__proxy_midiInGetNumDevs PROC
    jmp QWORD PTR [orig_midiInGetNumDevs]
__proxy_midiInGetNumDevs ENDP

__proxy_midiInMessage PROC
    jmp QWORD PTR [orig_midiInMessage]
__proxy_midiInMessage ENDP

__proxy_midiInOpen PROC
    jmp QWORD PTR [orig_midiInOpen]
__proxy_midiInOpen ENDP

__proxy_midiInPrepareHeader PROC
    jmp QWORD PTR [orig_midiInPrepareHeader]
__proxy_midiInPrepareHeader ENDP

__proxy_midiInReset PROC
    jmp QWORD PTR [orig_midiInReset]
__proxy_midiInReset ENDP

__proxy_midiInStart PROC
    jmp QWORD PTR [orig_midiInStart]
__proxy_midiInStart ENDP

__proxy_midiInStop PROC
    jmp QWORD PTR [orig_midiInStop]
__proxy_midiInStop ENDP

__proxy_midiInUnprepareHeader PROC
    jmp QWORD PTR [orig_midiInUnprepareHeader]
__proxy_midiInUnprepareHeader ENDP

__proxy_midiOutCacheDrumPatches PROC
    jmp QWORD PTR [orig_midiOutCacheDrumPatches]
__proxy_midiOutCacheDrumPatches ENDP

__proxy_midiOutCachePatches PROC
    jmp QWORD PTR [orig_midiOutCachePatches]
__proxy_midiOutCachePatches ENDP

__proxy_midiOutClose PROC
    jmp QWORD PTR [orig_midiOutClose]
__proxy_midiOutClose ENDP

__proxy_midiOutGetDevCapsA PROC
    jmp QWORD PTR [orig_midiOutGetDevCapsA]
__proxy_midiOutGetDevCapsA ENDP

__proxy_midiOutGetDevCapsW PROC
    jmp QWORD PTR [orig_midiOutGetDevCapsW]
__proxy_midiOutGetDevCapsW ENDP

__proxy_midiOutGetErrorTextA PROC
    jmp QWORD PTR [orig_midiOutGetErrorTextA]
__proxy_midiOutGetErrorTextA ENDP

__proxy_midiOutGetErrorTextW PROC
    jmp QWORD PTR [orig_midiOutGetErrorTextW]
__proxy_midiOutGetErrorTextW ENDP

__proxy_midiOutGetID PROC
    jmp QWORD PTR [orig_midiOutGetID]
__proxy_midiOutGetID ENDP

__proxy_midiOutGetNumDevs PROC
    jmp QWORD PTR [orig_midiOutGetNumDevs]
__proxy_midiOutGetNumDevs ENDP

__proxy_midiOutGetVolume PROC
    jmp QWORD PTR [orig_midiOutGetVolume]
__proxy_midiOutGetVolume ENDP

__proxy_midiOutLongMsg PROC
    jmp QWORD PTR [orig_midiOutLongMsg]
__proxy_midiOutLongMsg ENDP

__proxy_midiOutMessage PROC
    jmp QWORD PTR [orig_midiOutMessage]
__proxy_midiOutMessage ENDP

__proxy_midiOutOpen PROC
    jmp QWORD PTR [orig_midiOutOpen]
__proxy_midiOutOpen ENDP

__proxy_midiOutPrepareHeader PROC
    jmp QWORD PTR [orig_midiOutPrepareHeader]
__proxy_midiOutPrepareHeader ENDP

__proxy_midiOutReset PROC
    jmp QWORD PTR [orig_midiOutReset]
__proxy_midiOutReset ENDP

__proxy_midiOutSetVolume PROC
    jmp QWORD PTR [orig_midiOutSetVolume]
__proxy_midiOutSetVolume ENDP

__proxy_midiOutShortMsg PROC
    jmp QWORD PTR [orig_midiOutShortMsg]
__proxy_midiOutShortMsg ENDP

__proxy_midiOutUnprepareHeader PROC
    jmp QWORD PTR [orig_midiOutUnprepareHeader]
__proxy_midiOutUnprepareHeader ENDP

__proxy_midiStreamClose PROC
    jmp QWORD PTR [orig_midiStreamClose]
__proxy_midiStreamClose ENDP

__proxy_midiStreamOpen PROC
    jmp QWORD PTR [orig_midiStreamOpen]
__proxy_midiStreamOpen ENDP

__proxy_midiStreamOut PROC
    jmp QWORD PTR [orig_midiStreamOut]
__proxy_midiStreamOut ENDP

__proxy_midiStreamPause PROC
    jmp QWORD PTR [orig_midiStreamPause]
__proxy_midiStreamPause ENDP

__proxy_midiStreamPosition PROC
    jmp QWORD PTR [orig_midiStreamPosition]
__proxy_midiStreamPosition ENDP

__proxy_midiStreamProperty PROC
    jmp QWORD PTR [orig_midiStreamProperty]
__proxy_midiStreamProperty ENDP

__proxy_midiStreamRestart PROC
    jmp QWORD PTR [orig_midiStreamRestart]
__proxy_midiStreamRestart ENDP

__proxy_midiStreamStop PROC
    jmp QWORD PTR [orig_midiStreamStop]
__proxy_midiStreamStop ENDP

__proxy_mixerClose PROC
    jmp QWORD PTR [orig_mixerClose]
__proxy_mixerClose ENDP

__proxy_mixerGetControlDetailsA PROC
    jmp QWORD PTR [orig_mixerGetControlDetailsA]
__proxy_mixerGetControlDetailsA ENDP

__proxy_mixerGetControlDetailsW PROC
    jmp QWORD PTR [orig_mixerGetControlDetailsW]
__proxy_mixerGetControlDetailsW ENDP

__proxy_mixerGetDevCapsA PROC
    jmp QWORD PTR [orig_mixerGetDevCapsA]
__proxy_mixerGetDevCapsA ENDP

__proxy_mixerGetDevCapsW PROC
    jmp QWORD PTR [orig_mixerGetDevCapsW]
__proxy_mixerGetDevCapsW ENDP

__proxy_mixerGetID PROC
    jmp QWORD PTR [orig_mixerGetID]
__proxy_mixerGetID ENDP

__proxy_mixerGetLineControlsA PROC
    jmp QWORD PTR [orig_mixerGetLineControlsA]
__proxy_mixerGetLineControlsA ENDP

__proxy_mixerGetLineControlsW PROC
    jmp QWORD PTR [orig_mixerGetLineControlsW]
__proxy_mixerGetLineControlsW ENDP

__proxy_mixerGetLineInfoA PROC
    jmp QWORD PTR [orig_mixerGetLineInfoA]
__proxy_mixerGetLineInfoA ENDP

__proxy_mixerGetLineInfoW PROC
    jmp QWORD PTR [orig_mixerGetLineInfoW]
__proxy_mixerGetLineInfoW ENDP

__proxy_mixerGetNumDevs PROC
    jmp QWORD PTR [orig_mixerGetNumDevs]
__proxy_mixerGetNumDevs ENDP

__proxy_mixerMessage PROC
    jmp QWORD PTR [orig_mixerMessage]
__proxy_mixerMessage ENDP

__proxy_mixerOpen PROC
    jmp QWORD PTR [orig_mixerOpen]
__proxy_mixerOpen ENDP

__proxy_mixerSetControlDetails PROC
    jmp QWORD PTR [orig_mixerSetControlDetails]
__proxy_mixerSetControlDetails ENDP

__proxy_mmDrvInstall PROC
    jmp QWORD PTR [orig_mmDrvInstall]
__proxy_mmDrvInstall ENDP

__proxy_mmGetCurrentTask PROC
    jmp QWORD PTR [orig_mmGetCurrentTask]
__proxy_mmGetCurrentTask ENDP

__proxy_mmTaskBlock PROC
    jmp QWORD PTR [orig_mmTaskBlock]
__proxy_mmTaskBlock ENDP

__proxy_mmTaskCreate PROC
    jmp QWORD PTR [orig_mmTaskCreate]
__proxy_mmTaskCreate ENDP

__proxy_mmTaskSignal PROC
    jmp QWORD PTR [orig_mmTaskSignal]
__proxy_mmTaskSignal ENDP

__proxy_mmTaskYield PROC
    jmp QWORD PTR [orig_mmTaskYield]
__proxy_mmTaskYield ENDP

__proxy_mmioAdvance PROC
    jmp QWORD PTR [orig_mmioAdvance]
__proxy_mmioAdvance ENDP

__proxy_mmioAscend PROC
    jmp QWORD PTR [orig_mmioAscend]
__proxy_mmioAscend ENDP

__proxy_mmioClose PROC
    jmp QWORD PTR [orig_mmioClose]
__proxy_mmioClose ENDP

__proxy_mmioCreateChunk PROC
    jmp QWORD PTR [orig_mmioCreateChunk]
__proxy_mmioCreateChunk ENDP

__proxy_mmioDescend PROC
    jmp QWORD PTR [orig_mmioDescend]
__proxy_mmioDescend ENDP

__proxy_mmioFlush PROC
    jmp QWORD PTR [orig_mmioFlush]
__proxy_mmioFlush ENDP

__proxy_mmioGetInfo PROC
    jmp QWORD PTR [orig_mmioGetInfo]
__proxy_mmioGetInfo ENDP

__proxy_mmioInstallIOProcA PROC
    jmp QWORD PTR [orig_mmioInstallIOProcA]
__proxy_mmioInstallIOProcA ENDP

__proxy_mmioInstallIOProcW PROC
    jmp QWORD PTR [orig_mmioInstallIOProcW]
__proxy_mmioInstallIOProcW ENDP

__proxy_mmioOpenA PROC
    jmp QWORD PTR [orig_mmioOpenA]
__proxy_mmioOpenA ENDP

__proxy_mmioOpenW PROC
    jmp QWORD PTR [orig_mmioOpenW]
__proxy_mmioOpenW ENDP

__proxy_mmioRead PROC
    jmp QWORD PTR [orig_mmioRead]
__proxy_mmioRead ENDP

__proxy_mmioRenameA PROC
    jmp QWORD PTR [orig_mmioRenameA]
__proxy_mmioRenameA ENDP

__proxy_mmioRenameW PROC
    jmp QWORD PTR [orig_mmioRenameW]
__proxy_mmioRenameW ENDP

__proxy_mmioSeek PROC
    jmp QWORD PTR [orig_mmioSeek]
__proxy_mmioSeek ENDP

__proxy_mmioSendMessage PROC
    jmp QWORD PTR [orig_mmioSendMessage]
__proxy_mmioSendMessage ENDP

__proxy_mmioSetBuffer PROC
    jmp QWORD PTR [orig_mmioSetBuffer]
__proxy_mmioSetBuffer ENDP

__proxy_mmioSetInfo PROC
    jmp QWORD PTR [orig_mmioSetInfo]
__proxy_mmioSetInfo ENDP

__proxy_mmioStringToFOURCCA PROC
    jmp QWORD PTR [orig_mmioStringToFOURCCA]
__proxy_mmioStringToFOURCCA ENDP

__proxy_mmioStringToFOURCCW PROC
    jmp QWORD PTR [orig_mmioStringToFOURCCW]
__proxy_mmioStringToFOURCCW ENDP

__proxy_mmioWrite PROC
    jmp QWORD PTR [orig_mmioWrite]
__proxy_mmioWrite ENDP

__proxy_mmsystemGetVersion PROC
    jmp QWORD PTR [orig_mmsystemGetVersion]
__proxy_mmsystemGetVersion ENDP

__proxy_sndPlaySoundA PROC
    jmp QWORD PTR [orig_sndPlaySoundA]
__proxy_sndPlaySoundA ENDP

__proxy_sndPlaySoundW PROC
    jmp QWORD PTR [orig_sndPlaySoundW]
__proxy_sndPlaySoundW ENDP

__proxy_timeBeginPeriod PROC
    jmp QWORD PTR [orig_timeBeginPeriod]
__proxy_timeBeginPeriod ENDP

__proxy_timeEndPeriod PROC
    jmp QWORD PTR [orig_timeEndPeriod]
__proxy_timeEndPeriod ENDP

__proxy_timeGetDevCaps PROC
    jmp QWORD PTR [orig_timeGetDevCaps]
__proxy_timeGetDevCaps ENDP

__proxy_timeGetSystemTime PROC
    jmp QWORD PTR [orig_timeGetSystemTime]
__proxy_timeGetSystemTime ENDP

__proxy_timeGetTime PROC
    jmp QWORD PTR [orig_timeGetTime]
__proxy_timeGetTime ENDP

__proxy_timeKillEvent PROC
    jmp QWORD PTR [orig_timeKillEvent]
__proxy_timeKillEvent ENDP

__proxy_timeSetEvent PROC
    jmp QWORD PTR [orig_timeSetEvent]
__proxy_timeSetEvent ENDP

__proxy_waveInAddBuffer PROC
    jmp QWORD PTR [orig_waveInAddBuffer]
__proxy_waveInAddBuffer ENDP

__proxy_waveInClose PROC
    jmp QWORD PTR [orig_waveInClose]
__proxy_waveInClose ENDP

__proxy_waveInGetDevCapsA PROC
    jmp QWORD PTR [orig_waveInGetDevCapsA]
__proxy_waveInGetDevCapsA ENDP

__proxy_waveInGetDevCapsW PROC
    jmp QWORD PTR [orig_waveInGetDevCapsW]
__proxy_waveInGetDevCapsW ENDP

__proxy_waveInGetErrorTextA PROC
    jmp QWORD PTR [orig_waveInGetErrorTextA]
__proxy_waveInGetErrorTextA ENDP

__proxy_waveInGetErrorTextW PROC
    jmp QWORD PTR [orig_waveInGetErrorTextW]
__proxy_waveInGetErrorTextW ENDP

__proxy_waveInGetID PROC
    jmp QWORD PTR [orig_waveInGetID]
__proxy_waveInGetID ENDP

__proxy_waveInGetNumDevs PROC
    jmp QWORD PTR [orig_waveInGetNumDevs]
__proxy_waveInGetNumDevs ENDP

__proxy_waveInGetPosition PROC
    jmp QWORD PTR [orig_waveInGetPosition]
__proxy_waveInGetPosition ENDP

__proxy_waveInMessage PROC
    jmp QWORD PTR [orig_waveInMessage]
__proxy_waveInMessage ENDP

__proxy_waveInOpen PROC
    jmp QWORD PTR [orig_waveInOpen]
__proxy_waveInOpen ENDP

__proxy_waveInPrepareHeader PROC
    jmp QWORD PTR [orig_waveInPrepareHeader]
__proxy_waveInPrepareHeader ENDP

__proxy_waveInReset PROC
    jmp QWORD PTR [orig_waveInReset]
__proxy_waveInReset ENDP

__proxy_waveInStart PROC
    jmp QWORD PTR [orig_waveInStart]
__proxy_waveInStart ENDP

__proxy_waveInStop PROC
    jmp QWORD PTR [orig_waveInStop]
__proxy_waveInStop ENDP

__proxy_waveInUnprepareHeader PROC
    jmp QWORD PTR [orig_waveInUnprepareHeader]
__proxy_waveInUnprepareHeader ENDP

__proxy_waveOutBreakLoop PROC
    jmp QWORD PTR [orig_waveOutBreakLoop]
__proxy_waveOutBreakLoop ENDP

__proxy_waveOutClose PROC
    jmp QWORD PTR [orig_waveOutClose]
__proxy_waveOutClose ENDP

__proxy_waveOutGetDevCapsA PROC
    jmp QWORD PTR [orig_waveOutGetDevCapsA]
__proxy_waveOutGetDevCapsA ENDP

__proxy_waveOutGetDevCapsW PROC
    jmp QWORD PTR [orig_waveOutGetDevCapsW]
__proxy_waveOutGetDevCapsW ENDP

__proxy_waveOutGetErrorTextA PROC
    jmp QWORD PTR [orig_waveOutGetErrorTextA]
__proxy_waveOutGetErrorTextA ENDP

__proxy_waveOutGetErrorTextW PROC
    jmp QWORD PTR [orig_waveOutGetErrorTextW]
__proxy_waveOutGetErrorTextW ENDP

__proxy_waveOutGetID PROC
    jmp QWORD PTR [orig_waveOutGetID]
__proxy_waveOutGetID ENDP

__proxy_waveOutGetNumDevs PROC
    jmp QWORD PTR [orig_waveOutGetNumDevs]
__proxy_waveOutGetNumDevs ENDP

__proxy_waveOutGetPitch PROC
    jmp QWORD PTR [orig_waveOutGetPitch]
__proxy_waveOutGetPitch ENDP

__proxy_waveOutGetPlaybackRate PROC
    jmp QWORD PTR [orig_waveOutGetPlaybackRate]
__proxy_waveOutGetPlaybackRate ENDP

__proxy_waveOutGetPosition PROC
    jmp QWORD PTR [orig_waveOutGetPosition]
__proxy_waveOutGetPosition ENDP

__proxy_waveOutGetVolume PROC
    jmp QWORD PTR [orig_waveOutGetVolume]
__proxy_waveOutGetVolume ENDP

__proxy_waveOutMessage PROC
    jmp QWORD PTR [orig_waveOutMessage]
__proxy_waveOutMessage ENDP

__proxy_waveOutOpen PROC
    jmp QWORD PTR [orig_waveOutOpen]
__proxy_waveOutOpen ENDP

__proxy_waveOutPause PROC
    jmp QWORD PTR [orig_waveOutPause]
__proxy_waveOutPause ENDP

__proxy_waveOutPrepareHeader PROC
    jmp QWORD PTR [orig_waveOutPrepareHeader]
__proxy_waveOutPrepareHeader ENDP

__proxy_waveOutReset PROC
    jmp QWORD PTR [orig_waveOutReset]
__proxy_waveOutReset ENDP

__proxy_waveOutRestart PROC
    jmp QWORD PTR [orig_waveOutRestart]
__proxy_waveOutRestart ENDP

__proxy_waveOutSetPitch PROC
    jmp QWORD PTR [orig_waveOutSetPitch]
__proxy_waveOutSetPitch ENDP

__proxy_waveOutSetPlaybackRate PROC
    jmp QWORD PTR [orig_waveOutSetPlaybackRate]
__proxy_waveOutSetPlaybackRate ENDP

__proxy_waveOutSetVolume PROC
    jmp QWORD PTR [orig_waveOutSetVolume]
__proxy_waveOutSetVolume ENDP

__proxy_waveOutUnprepareHeader PROC
    jmp QWORD PTR [orig_waveOutUnprepareHeader]
__proxy_waveOutUnprepareHeader ENDP

__proxy_waveOutWrite PROC
    jmp QWORD PTR [orig_waveOutWrite]
__proxy_waveOutWrite ENDP

__proxy_ord2 PROC
    jmp QWORD PTR [orig___proxy_ord2]
__proxy_ord2 ENDP

END
